### PR TITLE
UTC based timestamps

### LINKED ISSUE #2122: use UTC based timestamps
We use in mscolab `datetime.datetime.now() `
This can have a timezone issue, we should replace it by a timezone based on UTC
`datetime.datetime.now(tz=datetime.timezone.utc)`

### PR DESCRIPTION
**Pull request by Shaheer-Ahmd**
**Purpose of PR?**:
We use in mscolab `datetime.datetime.now() `
This can have a timezone issue, we should replace it by a timezone based on UTC
`datetime.datetime.now(tz=datetime.timezone.utc)`
Fixes #2122 

**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Does this PR results in some Documentation changes?**
_If yes, include the list of Documentation changes_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (Non-API breaking changes that adds functionality)
- [ ] PR Title follows the convention of  `<type>: <subject>`
- [ ] Commit has unit tests

### CODE REVIEW

**Comment by Shaheer-Ahmd** [comment]
@ReimarBauer I have converted the datetimes (in mscolib and its tests) to UTC based timestamps as you requested in #2122 . Please let me know if you want this change throughout the entire codebase or if any other change is needed.

**Comment by ReimarBauer** [comment]
Hi @Shaheer-Ahmd see test output related to your changes.

**Comment by ReimarBauer** [comment]
There is a failing test after your change
https://github.com/Open-MSS/MSS/actions/runs/7400753920/job/20156627131?pr=2126#step:10:4847

**Comment by Shaheer-Ahmd** [comment]
Okay, I will look into it.

**Pull request closed without merging**
