### PR TITLE
Fix botched merge from 14 Aug 23 in mscolab.py

### LINKED ISSUE #1969: another fatal, uncaught timeout-related exception in mscolab upon activating an operation
```
2023-08-30 08:49:24,850 (qt.excepthook:183): CRITICAL: MSS Version: 8.2.0
2023-08-30 08:49:24,850 (qt.excepthook:184): CRITICAL: Python Version: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
2023-08-30 08:49:24,857 (qt.excepthook:185): CRITICAL: Platform: Linux-6.1.0-10-amd64-x86_64-with-glibc2.36 (('64bit', 'ELF'))
2023-08-30 08:49:24,857 (qt.excepthook:186): CRITICAL: Fatal error: Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/anaconda3/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/anaconda3/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/anaconda3/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:990: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/opt/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 1650, in set_active_op_id
    requests.post(f'{self.mscolab_server_url}/set_last_used', data=data,
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 702, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Read timed out. (read timeout=2)

```

### PR DESCRIPTION
**Pull request by joernu76**
Fixes #1969

**Purpose of PR?**:

Fixes #

**Does this PR introduce a breaking change?**
no

### CODE REVIEW

**Comment by joernu76** [comment]
I tried to recreate the merge from 14 Aug 2023 and tried to add the stuff I think was missing from my fixes back into develop. This should align stable and develop greatly.

**Review by ReimarBauer — COMMENTED** [review]
I created a test_for_leave op (category:devel) on the staging server you and me are added. When I get the OP pushed into the navigation and click on it, I get this failure. 
Also the navigation elements remain inactive for me.

On relogin I don't have this.


branch develop: Same problem
branch stable: it works perfect

So we broke this in develop.

```
Fatal error in MSS 8.3.0 on Linux-6.2.0-10018-tuxedo-x86_64-with-glibc2.35
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 1707, in set_active_op_id
    self.active_operation_category = item.operation_category
AttributeError: 'QListWidgetItem' object has no attribute 'operation_category'
```
The peek shows a pushed operation into my account and what happens afterwards.

problem_in_develop

**Comment by ReimarBauer** [comment]
I had not tracked it further down, if that happens with the merge too. Maybe you can look on it within this PR? Or we create a different PR. (I am looking for writing a test for that problem, so it gets easier catched.)

**Comment by joernu76** [comment]
Again, I could only properly review *my* extensive changes to mscolab.py. AFAIK, you changed some things with the category stuff. I can try to have a look, but it might be more efficient if you compare the files. give me a second.

**Comment by joernu76** [comment]
Both develop *and* stable seem to have a bug in category, where both a "catgegory" and "operation_category" attribute is set. I added a fix (and a resort to make comparing the set attributes simpler).
This needs a fix in stable as well, though, so I am not sure if this is the error you have there.
It coould explain your error behaviour though.
I prepare a fix for stable as well.

**Comment by ReimarBauer** [comment]
> Both develop _and_ stable seem to have a bug in category, where both a "catgegory" and "operation_category" attribute is set. I added a fix (and a resort to make comparing the set attributes simpler). This needs a fix in stable as well, though, so I am not sure if this is the error you have there. It coould explain your error behaviour though. I prepare a fix for stable as well.

I recognized that the problem above is also in ju_special, I create a seperate issue for that.  With the push also a reload of the operations or something similiar needs to be triggered. The reload was the past "slow" solution

**Review by ReimarBauer — APPROVED** [review]
the merge was not covered enough by tests.

**Pull request merged**
