### PR TITLE
Default to newest init time

### LINKED ISSUE #824: Displayed newest initialisation time as default
When on a MSS server multiple forecast data sets with different initialisation times are present, the default setting should be to disply the newest initialisation time. This is the most likely to be looked upon.
This is currently not the case. Please fix it.

### PR DESCRIPTION
**Pull request by Marilyth**
Fixes #824 
1. When a layer gets constructed, default to its newest initialisation time.
2. Improve carry-over logic. 
    Only carry over parameters that have been explicitly changed by the user, otherwise keep the default.
    Save carry-over parameters as to not lose them after a layer didn't support them.
3. Filter valid times to only show times after the selected init time

### CODE REVIEW

**Comment by joernu76** [comment]
Mmmh.
I "run immediately into the wall" that the init time was updated to the most recent one, but the forecast time is still the old one and thus invalid.
I feel this is getting out of hand...

**Comment by joernu76** [comment]
Ran into this error:
```
CRITICAL: Platform: Linux-5.10.0-6-amd64-x86_64-with-glibc2.10 (('64bit', 'ELF'))
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/wms_control.py", line 1071, in init_time_changed
    self.multilayers.get_current_layer().set_itime(self.cbInitTime.currentText())
  File "/home/icg173/src/mss/mslib/msui/multilayers.py", line 642, in set_itime
    self.set_vtime()
TypeError: set_vtime() missing 1 required positional argument: 'vtime'

```

To reproduce:
init time on 2021-05-09T00 valid time on 2021-05-09T12
choose init time 2021-05-10T00 -> error

**Comment by Marilyth** [comment]
Careless mistake. Should be fixed now. Sorry!

**Review by joernu76 — APPROVED** [review]
Seems to work now.
I am not sure if the behaviour is really better than a persistance-less, much simpler solution. We need to try this logic out a bit.

**Pull request merged**
