### PR TITLE
mslib/mswms/_tests/test_utils.py renamed to mslib/mswms/_tests/test_targets.py

### PR DESCRIPTION
**Pull request by Nightfurex**

### CODE REVIEW

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
Hi,

have a look on the doc string too.

**Comment by Nightfurex** [comment]
sorry but which doc string ?

**Comment by ReimarBauer** [comment]
> sorry but which doc string ?

you are right, that will be soon there, after I merged stable to development.

**Comment by ReimarBauer** [comment]
@Nightfurex Hi, please have a look on the merge conflict.

**Pull request closed without merging**
