### PR TITLE
add app.route for gallery mss/static/plots

### LINKED ISSUE #1368: gallery plots not shown on website, refactor remove url-prefix
in index.py APP.route for /mss/static/plots/ to STATIC_LOCATION/plots/*.png missing

### PR DESCRIPTION
**Pull request by gisi90**
fixes #1368

### CODE REVIEW

**Comment by ReimarBauer** [comment]
please add a test for this, and if it is a bug it needs to go to stable

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
please send a PR to stable

also a test for this is welcome.  

And have a look into the issue, I added two examples.

**Comment by gisi90** [comment]
correct use of url-prefix avoids this issue

**Comment by gisi90** [comment]
new purpose: get rid of url_prefix (see comments for issue  #1368)

**Comment by ReimarBauer** [comment]
please look also on this https://github.com/Open-MSS/MSS/issues/1370

**Comment by ReimarBauer** [comment]
We can reopen this when we continue

**Pull request closed without merging**
