### PR TITLE
update GSoC2024 projects in docs

### LINKED ISSUE #2516: update GSoC projects in our docs
After 2024 GSoC finals we have to update

https://mss.readthedocs.io/en/stable/development.html

### PR DESCRIPTION
**Pull request by sarthakvyas16**
* Further refactoring of mscolab

* Move (most) communication with server to ConnectionManager class to have
  consistent calls and error handling (e.g. timeout).
* More consistently use json() method of response.
* Removed single letter variables.

* Update mscolab_exceptions.py

update copyright string

---------

Co-authored-by: ReimarBauer <rb.proj@gmail.com>

**Purpose of PR?**:

Fixes #2516

Purpose of PR?:
Updated development.rst to reflect recent changes in mscolab.

Changes Made:

Added three lines in development.rst to clarify recent updates regarding the refactoring and use of the ConnectionManager class.
Does this PR introduce a breaking change?
No.

Checklist:

- []  Documentation changes only. Fixes #2516

### CODE REVIEW

**Comment by ReimarBauer** [comment]
Hi @sarthakvyas16 please can you send this change to our stable branch. We want this in the next minor or patch level release. The next major will need some more time.

Please also use a meaningful name for the PR string.

**Comment by sarthakvyas16** [comment]
Hi @ReimarBauer

I’ll go ahead and send this change to the stable branch. I’ll also come up with a meaningful name for the PR string.

Thanks for the update.

**Comment by sarthakvyas16** [comment]
Any other changes??

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
This looks like a merge request from develop to stable. 

You need to cherry pick your change and add it to a PR to stable

**Comment by ReimarBauer** [comment]
resolved meanwhile

**Pull request closed without merging**
