### PR TITLE
template_change

### LINKED ISSUE #1692: Addition of Issue and Pull Request templates.
Addition of Issue and Pull Request templates for better project standards and easily understand of the Pull Request or issues.

### PR DESCRIPTION
**Pull request by mastersans**
**Template Added**:

Fixes #1692  

**This PR is for the issue #1692  to add different template including:**

**Issue Template**
 _1.  Bug Report_
 _2. Feature Request_
**Pull Request Template**

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Commit has unit tests

### CODE REVIEW

**Comment by ReimarBauer** [comment]
"This change requires a documentation update"
 
 instead of describing this, the documentation change should be included.

**Comment by ReimarBauer** [comment]
> Breaking change (fix or feature that would cause existing functionality to not work as expected)

We do have only develop and stable branches. A PR doing this would go into develop, and there are API changes are "normal"

And when tests fail, the broken functionality will be recognized and needs fixes too.

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
see my comments

**Comment by mastersans** [comment]
> "This change requires a documentation update"
> 
> instead of describing this, the documentation change should be included.

Resolved !

**Comment by mastersans** [comment]
> > Breaking change (fix or feature that would cause existing functionality to not work as expected)
> 
> We do have only develop and stable branches. A PR doing this would go into develop, and there are API changes are "normal"
> 
> And when tests fail, the broken functionality will be recognized and needs fixes too.

Could you please clarify this once more

**Comment by ReimarBauer** [comment]
> > > Breaking change (fix or feature that would cause existing functionality to not work as expected)
> > 
> > 
> > We do have only develop and stable branches. A PR doing this would go into develop, and there are API changes are "normal"
> > And when tests fail, the broken functionality will be recognized and needs fixes too.
> 
> Could you please clarify this once more

We are based on semantic versioning.

This means after a release we do mostly bug fixes in stable and do release a patch release. We can also do enhancements when they don't change the API, this gives then based on stable the next minor release.

develop is used in general for all enhancements but we keep develop also useable. When some code is contributed, API is changed also the dependencies needs to be changed, otherwise we can't merge, because of test failure.

see alsos
https://mss.readthedocs.io/en/stable/development.html

**Comment by mastersans** [comment]
> > > > Breaking change (fix or feature that would cause existing functionality to not work as expected)
> > > 
> > > 
> > > We do have only develop and stable branches. A PR doing this would go into develop, and there are API changes are "normal"
> > > And when tests fail, the broken functionality will be recognized and needs fixes too.
> > 
> > 
> > Could you please clarify this once more
> 
> We are based on semantic versioning.
> 
> This means after a release we do mostly bug fixes in stable and do release a patch release. We can also do enhancements when they don't change the API, this gives then based on stable the next minor release.
> 
> develop is used in general for all enhancements but we keep develop also useable. When some code is contributed, API is changed also the dependencies needs to be changed, otherwise we can't merge, because of test failure.
> 
> see alsos https://mss.readthedocs.io/en/stable/development.html

So I have to modify the "Breaking Change" checkbox or to remove it entirely?

**Comment by ReimarBauer** [comment]
I guess removing is better. to remove that line

from versioning it is interesting to know, if the API changes by a feature. Mostly it does but when not we can add it to stable or later backport it. Depends if we want to make a bug fix releas on patch level or minor 

New feature (none API breaking change which adds functionality)

**Comment by mastersans** [comment]
> I guess removing is better. to remove that line
> 
> from versioning it is interesting to know, if the API changes by a feature. Mostly it does but when not we can add it to stable or later backport it. Depends if we want to make a bug fix releas on patch level or minor
> 
> New feature (none API breaking change which adds functionality)

Okay so i have changed the "New feature" checkbox and remove the "Breaking changes" one.

**Comment by ReimarBauer** [comment]
We verify the next PR if this works. Discussion between others in the recent Barcamp was different

**Review by ReimarBauer — APPROVED** [review]
Thx

**Pull request merged**
