### PR TITLE
add more entities to generic plots

### LINKED ISSUE #1826: add more entities to generic plots
"air_potential_temperature","mole_fraction_of_ammonia_in_air","mole_fraction_of_ethene_in_air","mole_fraction_of_formic_acid_in_air","mole_fraction_of_hydrogen_peroxide_in_air","mole_fraction_of_methanol_in_air"

are missing

### PR DESCRIPTION
**Pull request by joernu76**

### CODE REVIEW

**Comment by ReimarBauer** [comment]
I want the issues, because when we do a release I review all isues and can add Hints to the release notes, or on the documentation.

**Comment by ReimarBauer** [comment]
see https://github.com/Open-MSS/MSS/issues/1826

**Comment by ReimarBauer** [comment]
I have now several times seen a failing test on that port. 

HTTPConnectionPool(host='127.0.0.1', port=25484)

**Comment by joernu76** [comment]
Link? These changes should not cause any problems.

**Comment by ReimarBauer** [comment]
> Link? These changes should not cause any problems.

not now, I restarted the test. I currently note which ports are showing up when it gets into a timeout.

**Review by ReimarBauer — APPROVED** [review]
Thx

**Pull request merged**
