### PR TITLE
remove unnecssary lines from gitignore

### LINKED ISSUE #2070: Unnecessary line in .gitignore?
> https://github.com/Open-MSS/MSS/blob/f6b3ad110dbfaa12d439cadea6476dcd54d9328d/.gitignore#L28
> Where was that line coming from again? I cannot remember what this path was used for. Is it still required?

_Originally posted by @matrss in https://github.com/Open-MSS/MSS/pull/2069#discussion_r1384596047_

### PR DESCRIPTION
**Pull request by nilupulmanodya**
fixes #2070

### CODE REVIEW

**Comment by ReimarBauer** [comment]
I think there can be more removed
```
mslib/mss_config.py
mslib/mscolab/colabdata/
mslib/msui/wms_cache/
mslib/msui/mss.sideview.cfg
mslib/msui/mss.topview.cfg
mslib/msui/msui_settings.py
```

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
see comment, 
grep them in the modules, if they are not there defined for these dirs, they can be removed.

**Comment by nilupulmanodya** [comment]
> see comment, grep them in the modules, if they are not there defined for these dirs, they can be removed.

Just to clarify, do you mean to use like `grep -rnw . -e 'mslib/mss_config.py'` ? I don't understand the purpose of using grep for this. Could you please break this down bit?

**Comment by ReimarBauer** [comment]
> grep -rnw . -e 'mslib/mss_config.py

I meant lookup if there are reasons to have these lines. I think they are outdated and were not removed.

**Review by ReimarBauer — APPROVED** [review]
Thx

**Pull request merged**
