### PR TITLE
Merge current develop

### PR DESCRIPTION
**Pull request by nilupulmanodya**
**Purpose of PR?**:

Fixes #
Merge current develop

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Does this PR results in some Documentation changes?**
_If yes, include the list of Documentation changes_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (Non-API breaking changes that adds functionality)
- [ ] PR Title follows the convention of  `<type>: <subject>`
- [ ] Commit has unit tests

### CODE REVIEW

**Review by ReimarBauer — COMMENTED** [review]
I do another pass through, did looked with dirdiff and have not found a "merge issue"
unchecked is the pyuic5 conversion. 

In my dirs are also some unrelated files, e.g. patches. Ignore them in the picture.

dirdiff

**Comment by ReimarBauer** [comment]
@nilupulmanodya we need to move in a new task the .cookies dir to  e.g.  $HOME/.config/msui/webbrowser/.cookies
if it still creates on that place

**Review by ReimarBauer — APPROVED** [review]
Thx

**Comment by ReimarBauer** [comment]
@nilupulmanodya please undo the cookie change. A merge is complicated enough. It should not have new code.

This can go in the next PR. I meant that with a new task. Sorry for confusions.

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
please remove the new code which was yet not in develop or your branch

**Comment by nilupulmanodya** [comment]
> please remove the new code which was yet not in develop or your branch

Sorry for misunderstanding.. removed

**Review by ReimarBauer — APPROVED** [review]

**Pull request merged**
