### PR TITLE
Issue1341

### PR DESCRIPTION
**Pull request by joernu76**

### CODE REVIEW

**Review by gisi90 — APPROVED** [review]
looks good

**Comment by joernu76** [comment]
@ReimarBauer is sonja not allowed to approve or what else is the reason for this still being blocked?

**Comment by ReimarBauer** [comment]
> @ReimarBauer is sonja not allowed to approve or what else is the reason for this still being blocked?

see chat, I assume that there is a hidden feature/bug? I have not found something enabled in the settings which forces this. 
It behaves like a "review by an owner is required". This shows also the hint "At least 1 approving review is required by reviewers with write access." But this rule is not enabled.

**Review by ReimarBauer — APPROVED** [review]
thx

**Pull request merged**
