### PR TITLE
Stable to develop

### PR DESCRIPTION
**Pull request by joernu76**
CAREFUL

This merge request must be merged *without* semi-linear history.

### CODE REVIEW

**Comment by joernu76** [comment]
edit: posted to wrong thread

**Review by ReimarBauer — APPROVED** [review]
thx

**Comment by ReimarBauer** [comment]
> Ran into this error:
> 
> ```
> CRITICAL: Platform: Linux-5.10.0-6-amd64-x86_64-with-glibc2.10 (('64bit', 'ELF'))
> CRITICAL: Fatal error: Traceback (most recent call last):
>   File "/home/icg173/src/mss/mslib/msui/wms_control.py", line 1071, in init_time_changed
>     self.multilayers.get_current_layer().set_itime(self.cbInitTime.currentText())
>   File "/home/icg173/src/mss/mslib/msui/multilayers.py", line 642, in set_itime
>     self.set_vtime()
> TypeError: set_vtime() missing 1 required positional argument: 'vtime'
> ```
> 
> To reproduce:
> init time on 2021-05-09T00 valid time on 2021-05-09T12
> choose init time 2021-05-10T00 -> error

@joernu76 please file this as question/bug to stable

**Comment by joernu76** [comment]
Arg, sorry, wrong PR!

**Pull request merged**
