### PR TITLE
Update ui_shortcuts.py

### PR DESCRIPTION
**Pull request by Zerothlaw0095**
GSOC2024 ZEROTHLAW0095 UPDATES

**Purpose of PR?**:

Fixes #

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Does this PR results in some Documentation changes?**
_If yes, include the list of Documentation changes_

**Checklist:**
- [x] Bug fix. Fixes #<issue number>
- [x] New feature (Non-API breaking changes that adds functionality)
- [x] PR Title follows the convention of  `<type>: <subject>`
- [x] Commit has unit tests

### CODE REVIEW

**Comment by Zerothlaw0095** [comment]
If possible please check this proposal

**Comment by ReimarBauer** [comment]
Please can you link the issue. What does this solve?

And we need also the ui file.

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
see comments

**Comment by Zerothlaw0095** [comment]
1) This can enhance the UI while viewing the UI in a different modes.

2)More media queries have been added and better z transform visibility 

Please let me know if further clarifications are needed

**Comment by matrss** [comment]
The PR does not include a reasoning for the changes, nor do the changes make sense. This looks like it is just spam.

**Pull request closed without merging**
