### PR TITLE
makes conftest useable for windows devs , fixes #714

### LINKED ISSUE #714: conftest on windows has problems with backslashes
Also our conftest is not optimal currently for windows we found a dependency we asked for help on pyfilesystem2
 
https://github.com/PyFilesystem/pyfilesystem2/issues/454

### PR DESCRIPTION
**Pull request by ReimarBauer**
This PR enables testing for windows users.
Major Test problems are:
 - AttributeError: Can't pickle local object 'app_loader.<locals>.file'
 - PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen
 -  fs.errors.InvalidCharsInPath:  

This needs someone with windows python knowledge or iterative work by us.

### CODE REVIEW

**Comment by ReimarBauer** [comment]
AttributeError: Can't pickle local object 'app_loader..file'

 Python 3.8 changes the default mode of multiprocessing on MacOS to spawn instead of fork
 
windows uses also spawn.

https://docs.python.org/3/library/multiprocessing.html


fork is default on unix

**Comment by ReimarBauer** [comment]
for windows skipped all test which are based on multiprocessing. We need currently the fork method. windows knows only spawn.    

in a virtualized system with 6 cores used
220 passed, 143 skipped, 2981 warnings in 97.82s (0:01:37)

**Review by Marilyth — APPROVED** [review]
The tests run fine on Windows.
Though it is very unfortunate so many tests are skipped on Windows due to no fork support.
Perhaps there is a way to rewrite the tests to work on spawned processes entirely?

**Review by joernu76 — APPROVED** [review]

**Comment by joernu76** [comment]
I assume the problem is that spawn processes would not have everything "import"'ed already?
Maybe switch everything to QThreads where we're at it? We need QThreads for the background prefetching of maps anyway and QT offers nice interprocess-communication...?

**Comment by Marilyth** [comment]
Even just switching multiprocessing.Process to threading.Thread seems to have fixed a few test cases.
This is definitely fixable.

**Comment by ReimarBauer** [comment]
> I assume the problem is that spawn processes would not have everything "import"'ed already?
> Maybe switch everything to QThreads where we're at it? We need QThreads for the background prefetching of maps anyway and QT offers nice interprocess-communication...?

we need the flask server code refactored to solve various "AttributeError: Can't pickle local object" for spawn.
Tanish looks on the mscolab code. This is a bit work. 

related to macOS
https://bugs.python.org/issue33725


We meed multiprocessing for our webservices.

**Pull request merged**
