### PR TITLE
fix: Remove A005 from flake8 checks

### LINKED ISSUE #2312: builtin checker findings for mslib/plugins/io/csv.py and mslib/utils/time.py
@matrss seems the builtin checker was updated?

I rather don't want to rename the csv io plugin, the time utils module can maybe refactored renamed to times (just plural?)

@joernu76 What do you think? 

I assume we need to solve this in stable.

```
Successfully installed flake8-7.0.0 flake8-builtins-2.4.0 mccabe-0.7.0 pycodestyle-2.11.1 pyflakes-3.2.0
mslib/plugins/io/csv.py:0:1: A005 the module is shadowing a Python builtin module "csv"
mslib/utils/time.py:0:1: A005 the module is shadowing a Python builtin module "time"
2     A005 the module is shadowing a Python builtin module "csv"
2
```

### PR DESCRIPTION
**Pull request by joernu76**
This test does not provide sensible warnings, currently.

**Purpose of PR?**:

Fixes #2312 

**Does this PR introduce a breaking change?**

no
**If the changes in this PR are manually verified, list down the scenarios covered:**:
-

**Checklist:**
- [x] Bug fix. Fixes #<issue number>
- [ ] New feature (Non-API breaking changes that adds functionality)
- [ ] PR Title follows the convention of  `<type>: <subject>`
- [ ] Commit has unit tests

### CODE REVIEW

**Comment by matrss** [comment]
I think this should go to develop, since we don't even have the flake8-builtins checks on stable. If it is really wanted on stable then the change would also need to go into the tool:pytest section of setup.cfg. On develop this duplication is gone already.

**Comment by joernu76** [comment]
So to develop it goes.

In the flake8 test, I do not see either of the second or third command being output by github. i.e. the pip --upgrade pip command is shown, but neither the installation nor execution of flake8.

I presume flake8 is executed with the "0" as its output?

**Comment by matrss** [comment]
> In the flake8 test, I do not see either of the second or third command being output by github. i.e. the pip --upgrade pip command is shown, but neither the installation nor execution of flake8.

pip's output from installing flake8 and flake8-builtins is shown (from this line onwards: https://github.com/Open-MSS/MSS/actions/runs/8650673932/job/23719710583?pr=2317#step:4:25).

> I presume flake8 is executed with the "0" as its output?

Yes, usually flake8 wouldn't print anything when there is no warning, but due to either the --count or the --statistics option it prints the total number of warnings (which is 0 in this case).

**Review by matrss — APPROVED** [review]

**Comment by joernu76** [comment]
> > In the flake8 test, I do not see either of the second or third command being output by github. i.e. the pip --upgrade pip command is shown, but neither the installation nor execution of flake8.
> 
> pip's output from installing flake8 and flake8-builtins is shown (from this line onwards: https://github.com/Open-MSS/MSS/actions/runs/8650673932/job/23719710583?pr=2317#step:4:25).
> 
> > I presume flake8 is executed with the "0" as its output?
> 
> Yes, usually flake8 wouldn't print anything when there is no warning, but due to either the --count or the --statistics option it prints the total number of warnings (which is 0 in this case).

Ah, stupid me hasn't seen the ">" button, which hides all but the first command. Thanks.

**Pull request merged**
