### PR TITLE
Catch exceptions caused by timeouts

### LINKED ISSUE #1830: Crash/unhandled Exception during mscolab login (on bad connection)
[msui.log](https://github.com/Open-MSS/MSS/files/12159297/msui.log)

### PR DESCRIPTION
**Pull request by joernu76**

### CODE REVIEW

**Comment by ReimarBauer** [comment]
Got this tried with an unkown user password
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reimar/MASTER/MSS/mslib/msui/mscolab.py", line 257, in login_handler
    r = s.post(url, data=data, timeout=(2, 10))
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Read timed out. (read timeout=2)
CRITICAL: MSS Version: 8.1.1
CRITICAL: Python Version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
CRITICAL: Platform: Linux-6.2.0-10018-tuxedo-x86_64-with-glibc2.35 (('64bit', 'ELF'))
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reimar/MASTER/MSS/mslib/msui/mscolab.py", line 257, in login_handler
    r = s.post(url, data=data, timeout=(2, 10))
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Read timed out. (read timeout=2)
```

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
@joernu76 I found one more, can you look on this too?

**Comment by joernu76** [comment]
The changed version should capture this Exception as well.
However, this patch only prevents the unmitigated crash; it is not necessarily the best way to handle these errors with a disconnect.
I also wouldn't expect a TimeoutError for an unknown password...

**Comment by ReimarBauer** [comment]
> The changed version should capture this Exception as well. However, this patch only prevents the unmitigated crash; it is not necessarily the best way to handle these errors with a disconnect. I also wouldn't expect a TimeoutError for an unknown password...

I can repeat this on the next not so far train ride.

**Comment by ReimarBauer** [comment]
```
WARNING:root:Couldn't import mscolab_settings (ImportError:'No module named 'mscolab_settings''), using dummy config.
WARNING:root:No module named 'mswms_settings'. Can't generate gallery.
INFO: MSS Version: 8.1.1
INFO: Python Version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
INFO: Platform: Linux-6.2.0-10018-tuxedo-x86_64-with-glibc2.35 (('64bit', 'ELF'))
ERROR: unexpected error: <class 'requests.exceptions.ReadTimeout'> https://forecast.fz-juelich.de/token HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Read timed out. (read timeout=2)
Speicherzugriffsfehler

```

connect worked. during login I took a "tunnel" On next connect the app was closed with "memory fault"

**Comment by ReimarBauer** [comment]
retrieving data from the wms in a "tunnel"

```
ERROR:
<class 'requests.exceptions.ReadTimeout'>
HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Read timed out. (read timeout=30)

```

**Comment by joernu76** [comment]
"Speicherzugriffsfehler" does not sound good. we really cannot do something about that, can we?

**Comment by ReimarBauer** [comment]
> "Speicherzugriffsfehler" does not sound good. we really cannot do something about that, can we?

we could try to track it down by using the faulthandler.
https://stackoverflow.com/questions/16731115/how-to-debug-a-python-segmentation-fault/58825725#58825725

This may be related:
https://github.com/psf/requests/issues/6064

I have a rather old requests module in my mssenv and mssdev, 
requests                  2.28.2             pyhd8ed1ab_0    conda-forge

**Comment by ReimarBauer** [comment]
I think we should try this, it solves some of the problems. The segfault problem were also in the old code. Maybe it gets solved by the requests update. 

The trial amount of "reconnect" changes we should do in a different PR

**Review by ReimarBauer — APPROVED** [review]
we should try this. It is better as before

**Comment by ReimarBauer** [comment]
I clicked, "ready for review" so I could review and don't need to do it againg when state toggles

**Pull request merged**
