### PR TITLE
Create CONTRIBUTING.md

### LINKED ISSUE #643: Missing Code of conduct and Contributing documents
Hi, I see that your project don't have a Code of conduct.md and Contributing.md file
would you like me to Propose one for your team?
It will make your community profile stronger.

### PR DESCRIPTION
**Pull request by BobinMathew**
Issue [#643](https://github.com/Open-MSS/MSS/issues/643)

### CODE REVIEW

**Comment by ReimarBauer** [comment]
I got an idea what all I should describe here. 

Because we do release on conda-forge I derivate this better from our existing documentations:  https://mss.readthedocs.io/en/stable/development.html#creating-a-new-release

**Comment by BobinMathew** [comment]
Do you want to include these in the contributing file?
- update a fork of the mss-feedstock - set version string - set sha256 checksum of the tagged release - update dependencies
- rerender the feedstock by conda smithy
- send a pull request
- maintainer will merge if there is no error

**Comment by ReimarBauer** [comment]
Not all but the differences between stable and develop branch. And what gets into a stable (update) release. 
And how much coverage we want.  The code of conduct is quite similar to the old python code of conduct.  
I like it, but will read it after some sleep again.

Mostly we have to define the PR Workflow.

**Comment by BobinMathew** [comment]
> Mostly we have to define the PR Workflow.

Ok I guess we can work on Contribution file after this

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
because we don't build here I currently have problems with 1. 

I can merge this and refactor it afterwards. Currently I would start at  2.

And at the point we trust the automatism for a build process triggered we can think about how to add 1

We are new here and we need a bit time to set everything up and to figure how we don't fail.

**Review by ReimarBauer — APPROVED** [review]

**Pull request merged**
