### PR TITLE
removed excess blanks before fixations

### LINKED ISSUE #1362: meta.yaml uses to much blanks for fixations
We have in our meta.yaml https://github.com/Open-MSS/MSS/blob/develop/localbuild/meta.yaml
used fixations with one or more blanks. 

one blank is the correct definition

### PR DESCRIPTION
**Pull request by shivamshan**
- Removed some extra space before fixation in meta.yaml file.

Signed-off-by: Shivam Shandilya <shivam.stpaulsdarjeeling@gmail.com>

### CODE REVIEW

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
there are more lines with that wrong pattern. Please fix the others too.

**Comment by shivamshan** [comment]
@ReimarBauer are there any more changes required for this issue?

**Comment by ReimarBauer** [comment]
> @ReimarBauer are there any more changes required for this issue?

Please have a look on the merge conflict.

**Review by ReimarBauer — APPROVED** [review]
thx

**Pull request merged**
