### PR TITLE
Rename operation name

### LINKED ISSUE #1328: review communication state over socketio.
We have to review on all existing actions the communication state over socketio.

### PR DESCRIPTION
**Pull request by Jatin2020-24**

### CODE REVIEW

**Comment by Jatin2020-24** [comment]
rename_operation

This will show current changes.

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
checked a few more things now. merged too early. sorry. 

we should warn when a name is taken. Not by lookup because this can be used to guess OPs. Just if it not possible to tell "this name is taken" by  QtWidgets.QMessageBox.Warning / Error

exists

**Comment by ReimarBauer** [comment]
The list is updated
start

now we need also to update the image on the particpants opened views (window title and text)
renamed


When a client is triggered to reload_operations, we should check as client if the name changes of the selected operation and update afterwards the open views. If the client ist looking on a different operation or none we don't have to update.

**Comment by ReimarBauer** [comment]
if an OP is selected where the user is not creator the "rename Operation" dialog should become inactive. Currently I can use the action but it doesn't rename (that's correct behaviour)

**Review by ReimarBauer — APPROVED** [review]
thx for working on this.

**Pull request merged**
