### PR TITLE
Use decorator to make msui/mscolab code more readable

### PR DESCRIPTION
**Pull request by joernu76**
This draft shows how we can simplify the mscolab user verification as a further step in refactoring MSUI mscolab.

Tip: The MR becomes reviewable only iff one hides whitespace changes.

### CODE REVIEW

**Comment by joernu76** [comment]
The extra "_"/"_1"... parameters are necessary as QT provides additional parameters, but seemingly looks at the callback function to decide whether to pass them or not.

As next step I would see if a dedicated Exception could be used to force logout in the decorator to further simply all the error handling in the class methods.

**Comment by ReimarBauer** [comment]
Issue #2011 (linking)

We likly have to run all related tests with that config option disabled too.

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
hmm, not sure if I have in my verification setup, but I can't login currentliy

database seeded:
 python mslib/mscolab/mscolab.py db --seed
using on the UI the accound for a@notexisting.org and have the verification enabled

image

I get after login logged out

logoff

**Comment by ReimarBauer** [comment]
hmm, I can also not login again with the a user when I enabled skipping ot the ui based verification. 

b, c, do similiar

**Comment by ReimarBauer** [comment]
when I can update the configuration file I am not logged out. But a relogin doesn't too.

when_i_can_update

**Comment by joernu76** [comment]
> hmm, I can also not login again with the a user when I enabled skipping ot the ui based verification.
> 
> b, c, do similiar

Mmmh, I cannot replicate your problems with either the local nor the remote server. do you have more information from debug output or similar, what is failing?

**Comment by ReimarBauer** [comment]
```
2024-09-06 11:56:21,872 (msui_mainwindow.update_active_flight_track:799): DEBUG: update_active_flight_track
2024-09-06 11:56:21,872 (verify_user_token.verify_user_token:56): ERROR: unexpected error: <class 'requests.exceptions.MissingSchema'> Invalid URL 'test_authorized': No scheme supplied. Perhaps you meant https://test_authorized?
```

**Comment by ReimarBauer** [comment]
The above mentioned problems I can't reproduce in a different setup.

With `"mscolab_skip_verify_user_token": false,` restarting a connected localhost server I get on clicking an operation:

```
Fatal error in MSS 9.2.0 on Linux-6.8.0-101041-tuxedo-x86_64-with-glibc2.35
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 1735, in set_active_op_id
    logging.debug('set_active_op_id %s %s %s', item, item.op_id, self.active_op_id)
                                                     ^^^^^^^^^^
AttributeError: 'QListWidgetItem' object has no attribute 'op_id'
```

**Comment by ReimarBauer** [comment]
> The above mentioned problems I can't reproduce in a different setup.
> 
> With `"mscolab_skip_verify_user_token": false,` restarting a connected localhost server I get on clicking an operation:
> 
> ```
> Fatal error in MSS 9.2.0 on Linux-6.8.0-101041-tuxedo-x86_64-with-glibc2.35
> Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
> 
> Please report bugs in MSS to https://github.com/Open-MSS/MSS
> 
> Information about the fatal error:
> 
> Traceback (most recent call last):
>   File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 1735, in set_active_op_id
>     logging.debug('set_active_op_id %s %s %s', item, item.op_id, self.active_op_id)
>                                                      ^^^^^^^^^^
> AttributeError: 'QListWidgetItem' object has no attribute 'op_id'
> ```

This is not easy to reproduce. I was not able to make a gifcycle.
This multiple clickaway widgets may have been before too,  I didn't check, but no crash.

**Comment by ReimarBauer** [comment]
> The above mentioned problems I can't reproduce in a different setup.
> 
> With `"mscolab_skip_verify_user_token": false,` restarting a connected localhost server I get on clicking an operation:
> 
> ```
> Fatal error in MSS 9.2.0 on Linux-6.8.0-101041-tuxedo-x86_64-with-glibc2.35
> Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
> 
> Please report bugs in MSS to https://github.com/Open-MSS/MSS
> 
> Information about the fatal error:
> 
> Traceback (most recent call last):
>   File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 1735, in set_active_op_id
>     logging.debug('set_active_op_id %s %s %s', item, item.op_id, self.active_op_id)
>                                                      ^^^^^^^^^^
> AttributeError: 'QListWidgetItem' object has no attribute 'op_id'
> ```

This is not easy to reproduce. I was not able to make a gifcycle.
This multiple clickaway widgets may have been before too,  I didn't check, but no crash.


multiple_messages_to_click_away

**Comment by ReimarBauer** [comment]
with mscolab_skip_verify_user_token I can crash it
```
Fatal error in MSS 9.2.0 on Linux-6.8.0-101041-tuxedo-x86_64-with-glibc2.35
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 82, in wrapper
    return func(*args, **vargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 2007, in handle_waypoints_changed
    self.conn.save_file(self.token, self.active_op_id, xml_content, comment=None,
  File "/home/reimar/MAIN/MSS/mslib/msui/socket_control.py", line 205, in save_file
    self.sio.emit('file-save', {
  File "/home/reimar/Miniforge/envs/mssdev/lib/python3.11/site-packages/socketio/client.py", line 209, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.
```

skip_true

**Comment by ReimarBauer** [comment]
I removed some gifcycle posts, because  I am not sure if I used the  right branch so I do repeat and record.
The idea is always connect to a localhost mscolab server and then cycle the server start. By this a used token is invalid

## First case mscolab_skip_verify_user_token is False

### only login restart server:
After multiple ok, logout done

multiple_times_ok

### work on a flightpath and cycle server start

does as expected

remove_operation_track_after_server_start_cycle

## Second case mscolab_skip_verify_user_token is True (default)
### only login restart server:
Crash
```
Fatal error in MSS 9.2.0 on Linux-6.8.0-101041-tuxedo-x86_64-with-glibc2.35
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 82, in wrapper
    return func(*args, **vargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 1863, in set_active_op_id
    window.setFlightTrackModel(self.waypoints_model)
  File "/home/reimar/MAIN/MSS/mslib/msui/viewwindows.py", line 250, in setFlightTrackModel
    super().setFlightTrackModel(model)
  File "/home/reimar/MAIN/MSS/mslib/msui/viewwindows.py", line 112, in setFlightTrackModel
    self.setWindowTitle(self.windowTitle().replace(self.waypoints_model.name, model.name))
                                                                              ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
```

crash_mscolab_skip_verify_user_token_is_True_only_login


### work on a flightpath and cycle server start
Crash

```
Fatal error in MSS 9.2.0 on Linux-6.8.0-101041-tuxedo-x86_64-with-glibc2.35
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 82, in wrapper
    return func(*args, **vargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 2007, in handle_waypoints_changed
    self.conn.save_file(self.token, self.active_op_id, xml_content, comment=None,
  File "/home/reimar/MAIN/MSS/mslib/msui/socket_control.py", line 205, in save_file
    self.sio.emit('file-save', {
  File "/home/reimar/Miniforge/envs/mssdev/lib/python3.11/site-packages/socketio/client.py", line 209, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.
```

crash_mscolab_skip_verify_user_token_is_True_work_on_flighttrack

**Comment by ReimarBauer** [comment]
> > hmm, I can also not login again with the a user when I enabled skipping ot the ui based verification.
> > b, c, do similiar
> 
> Mmmh, I cannot replicate your problems with either the local nor the remote server. do you have more information from debug output or similar, what is failing?

I cannot replicate those on an other system. I try to find what the difference in my setup is.

**Review by ReimarBauer — APPROVED** [review]
The problems are also in an unmodified version and needs to become addressed in a different task.

**Pull request merged**
