### PR TITLE
Check path doesn't contain illegal characters

### LINKED ISSUE #875: mscolab project name with blanks
It seems, that a mscolab project needs to be named without spaces or "special characters". This is displayed in the selection box when choosing "Add Project". However, if accitently a project name including a blank is typed in, there comse the error message "The path already exists"
If project names need to be without blanks, please drop a meaningful error message

### PR DESCRIPTION
**Pull request by Marilyth**
Adds a regex check before adding the project to make sure the path contains no spaces or special characters other than _ and - as a substitute for spaces.
fixes #875

### CODE REVIEW

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
if bool()

https://stackoverflow.com/questions/6576962/python-regular-expressions-return-true-false

**Comment by ReimarBauer** [comment]
We should convert this to a bool so True/False instead different types can be used.

Later for tests that makes that simpler

**Comment by Marilyth** [comment]
We use None for ifs all over MSS. I am not sure why it should be different here but okay.

**Comment by ReimarBauer** [comment]
ok, then we do that later when we want to refactor that, agreed.

**Review by ReimarBauer — DISMISSED** [review]
Thx

**Review by ReimarBauer — APPROVED** [review]
:)

**Pull request merged**
