### PR TITLE
Migrate existing thermodynamic functions to metpy functions

### LINKED ISSUE #1004: metpy migration
The metpy package is a well-maintained package containing a lot of useful routines for thermodynamics and interpolation. We should migrate as much of our code to their functions.

This issue shall serve to collect individual tasks of the migration. 

- [ ] add metpy to dependencies
- [ ] migrate mslib/thermolib.py rel_hum+sat_vapour_pressure function (i.e. fully remove)
- [ ] migrate mslib/thermolib.py virt_temp function (i.e. fully remove)
- [ ] migrate mslib/thermolib.py pot_temp function (i.e. fully remove)
- [ ] migrate mslib/thermolib.py eqpt_approxfunction (i.e. fully remove)
- [ ] fully remove spec_hum_from_pTd from mslib/thermolib.py 
- [ ] fully remove geop_thickness from mslib/thermolib.py 
- [ ] fully remove dewpoint_approx from mslib/thermolib.py 
- [ ] move units usage to metpy.units
- [ ] investigate interpolation routines and replace homegrown ones, if useful

### PR DESCRIPTION
**Pull request by Jatin2020-24**
Fixes: #1004 

- [x] add metpy to dependencies
- [x] migrate mslib/thermolib.py rel_hum+sat_vapour_pressure function (i.e. fully remove)
- [x] migrate mslib/thermolib.py virt_temp function (i.e. fully remove)
- [x] migrate mslib/thermolib.py pot_temp function (i.e. fully remove)
- [x] migrate mslib/thermolib.py eqpt_approxfunction (i.e. fully remove)
- [x] fully remove spec_hum_from_pTd from mslib/thermolib.py
- [x] fully remove geop_thickness from mslib/thermolib.py
- [x]  fully remove dewpoint_approx from mslib/thermolib.py
- [x] move units usage to metpy.units
- [ ] investigate interpolation routines and replace homegrown ones, if useful

### CODE REVIEW

**Comment by joernu76** [comment]
Good progress! Personally, I would do the calls to the metpy functions within the plotting classes (to be able to fully remove the thermolib.py file), but as an intermediate step it is probably better to follow your approach!

**Comment by joernu76** [comment]
I had a look at the probably last remaining actual error. This fixes it for me:
```diff --git a/mslib/thermolib.py b/mslib/thermolib.py
index 9226e702..56ddc11c 100644
--- a/mslib/thermolib.py
+++ b/mslib/thermolib.py
@@ -177,23 +177,6 @@ def pot_temp(p, t):
     return potential_temp
 
 
-def dewpoint(p, t, q):
-    """
-    Computes dewpoint temperature in [K] from pressure, temperature and specific humidity.
-
-    Arguments:
-    p -- pressure in [Pa]
-    t -- temperature in [K]
-    q -- specific humidity in [Kg/Kg]
-
-    Returns: dewpoint temperature in [K]. Same dimensions as the inputs.
-    """
-    p = units.Quantity(p, "Pa")
-    t = units.Quantity(t, "K")
-    dew_temp = mpcalc.dewpoint_from_specific_humidity(p, t, q)
-    return dew_temp.to('K')
-
-
 def eqpt_approx(p, t, q):
     """
     Computes equivalent potential temperature in [K] from pressure,
@@ -211,7 +194,7 @@ def eqpt_approx(p, t, q):
     """
     p = units.Quantity(p, "Pa")
     t = units.Quantity(t, "K")
-    dew_temp = dewpoint(p, t, q)
+    dew_temp = mpcalc.dewpoint_from_specific_humidity(p, t, q)
     eqpt_temp = mpcalc.equivalent_potential_temperature(p, t, dew_temp)
     return eqpt_temp.to('degC')
 


```
 The problem is the testless "addition" of units, which, in this case, added them twice (i.e. the units were "Pa Pa" instead of "Pa").

**Comment by joernu76** [comment]
To generally circumvent this problem, I would suggest to "discard" the units upon returning the results by "return var.to("K").magnitude" instead of "return var.to("K")".
This would also prevent similar issues in the future.
We will probably switch everything to arrays with units in the near future, but until then it is simpler to keep everything unit less outside the immediate metpy interaction.

**Comment by Jatin2020-24** [comment]
@joernu76 I've made changes as per your suggestion and errors are also fixed but now it's throwing attribute error in 
`mslib/msui/_tests/test_mscolab_project`. [Posted on slack ](https://mss-devel.slack.com/archives/C34ECMYFR/p1623562072046300).

**should we also migrate [omega_to_w](https://github.com/Open-MSS/MSS/blob/849dfe0b7b521fea256b32293e6b4f734ea75ad3/mslib/thermolib.py#L709) function to metpy.**

PS: Also not migrating [flightlevel2pressure](https://github.com/Open-MSS/MSS/blob/849dfe0b7b521fea256b32293e6b4f734ea75ad3/mslib/thermolib.py#L735) and [pressure2flightlevel](https://github.com/Open-MSS/MSS/blob/849dfe0b7b521fea256b32293e6b4f734ea75ad3/mslib/thermolib.py#L831) functions to metpy as they were having [issue](https://github.com/Open-MSS/MSS/issues/1025#issue-917301200) after 11Km.

**Comment by Jatin2020-24** [comment]
should we also migrate [omega_to_w](https://github.com/Open-MSS/MSS/blob/849dfe0b7b521fea256b32293e6b4f734ea75ad3/mslib/thermolib.py#L709) function to metpy. 

And  I am not migrating [flightlevel2pressure](https://github.com/Open-MSS/MSS/blob/849dfe0b7b521fea256b32293e6b4f734ea75ad3/mslib/thermolib.py#L735) and [pressure2flightlevel](https://github.com/Open-MSS/MSS/blob/849dfe0b7b521fea256b32293e6b4f734ea75ad3/mslib/thermolib.py#L831) functions to metpy as they were having [issue](https://github.com/Open-MSS/MSS/issues/1025#issue-917301200) after 11Km.

**Comment by joernu76** [comment]
The MSCOLAB test are, very sadly, not stable. Let's try rerunning them. We are working on that since quite some time, but have not yet understood the root cause for the behaviour as it seems to only occur on the github pipelines and not on our own computers.

**Comment by joernu76** [comment]
w.r.t. omega_to_w, yes, migrate it to metpy, please.
But we can merge also the current state and then proceed working on this in a future one. The end-state would be no thermolib.py and unit-aware arrays.
That partially goes beyond a first-timer issue, though.

**Review by joernu76 — APPROVED** [review]

**Comment by Jatin2020-24** [comment]
Thanks for your help and guidance.

**Pull request merged**
