### PR TITLE
install description changed to be based on conda-forge, Closes #689

### LINKED ISSUE #689: based on conda-forge only
We should check if we can be based on conda-forge channel only.

Because of ours and many others automated setups we use some much bandwidth of anaconda. That had recently  forced a change in the terms of service.

The mamba org works on sustainablilty of the open-source ananconda conda-forge channel and  there will be mirrors in the future.

### LINKED ISSUE #733: QT Version mismatch between different OS
We recognized today that we get on windows on a fresh installation 
- pyqt 5.12.3
- qt 5.12.9

and on linux
- pyqt 5.9.2
- qt 5.9.7

ui files using  QSpinBox with the 5.12.x designer created have an attribute StepType
 the conversion to the pyui has than an Attribute setStepType which does not exists in older versions.

```
AttributeError: 'QtCustomDoubleSpinBox' object has no attribute 'setStepType'.
```
because setStepType was introduced in [Qt 5.12 ](https://doc.qt.io/qt-5/qspinbox.html#setStepType)

### PR DESCRIPTION
**Pull request by ReimarBauer**

### CODE REVIEW

**Comment by ReimarBauer** [comment]
I assume the tests fail, because we have first to change the fundamental order in the testing docker environment. There we currently have 1. defaults than 2. conda-forge. This order can't build the fixation for qt.

**Comment by ReimarBauer** [comment]
Strange, locally with a complete new miniconda3 and the prefered configuration it did not crash and runs all tests

**Comment by Marilyth** [comment]
> I assume the tests fail, because we have first to change the fundamental order in the testing docker environment. There we currently have 1. defaults than 2. conda-forge. This order can't build the fixation for qt.

If the order is the issue, the testing.yml and xdist_testing.yml need to be adjusted, now that the order changed for the containers. They still reinstall with the old order. This could be done in a seperate PR or included in this one for a direct fix.
https://github.com/Open-MSS/MSS/blob/81a62a3f0f08d6a9815f1042b52dd99998bd951b/.github/workflows/testing.yml#L31

**Comment by ReimarBauer** [comment]
found it

```
-sqlalchemy                1.4.2            py39h3811e60_0    conda-forge
-sqlite                    3.35.2               h74cdb3f_0    conda-forge
+sqlalchemy                1.3.23           py39h3811e60_0    conda-forge
+sqlite                    3.35.0               hdfb4753_0  
```
stable to develop merge is missing

**Comment by ReimarBauer** [comment]
with my cleanup on my fork I closed this accidantly

**Review by joernu76 — APPROVED** [review]

**Pull request merged**
