### PR TITLE
Replace matplotlib grid parameter 'b' with 'visible'

### LINKED ISSUE #1955: MatplotlibDeprecationWarning from usage of parameter 'b' in grid()
```
  /home/icg149/Projects/MSS/mslib/mswms/mpl_vsec.py:135: MatplotlibDeprecationWarning: The 'b' parameter of grid() has been renamed 'visible' since Matplotlib 3.5; support for the old name will be dropped two minor releases later.
    ax.grid(b=True)
```

Fixing this should just be changing the keyword parameter name.

### PR DESCRIPTION
**Pull request by matrss**
**Purpose of PR?**:

Fixes #1955

**Does this PR introduce a breaking change?**

No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

test suite passes

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Does this PR results in some Documentation changes?**
_If yes, include the list of Documentation changes_

**Checklist:**
- [X] Bug fix. Fixes #1955
- [ ] New feature (Non-API breaking changes that adds functionality)
- [ ] PR Title follows the convention of  `<type>: <subject>`
- [ ] Commit has unit tests

### CODE REVIEW

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
pin in the meta.yaml  matplotlib >=3.7

**Comment by matrss** [comment]
We currently have an upper bound of <3.6 on matplotlib, due to #1579. Can this be lifted?

If your concern is that older matplotlib versions would not work with this patch: since we are currently on 3.5.3 as the latest version <3.6 we obviously do not need >=3.7 for this patch to work. But we should at least raise our lower bound to 3.5.3 I think.

**Comment by ReimarBauer** [comment]
current limitation of basemap is < 3.8
https://github.com/conda-forge/basemap-feedstock/blob/main/recipe/meta.yaml

**Comment by ReimarBauer** [comment]
we should have the lowest bound for this patch. Because we will uses basemap this will define what of matplotlib we will use from the upper.

**Comment by matrss** [comment]
Since basemap already specifies the upper bound to be <3.8 this propagates to mss as well, right? That would mean we don't need to specify it again. The reason we added <3.6 here was because there was not yet a release of basemap with the upper bound set on their side, but that reason does not apply anymore.

The current state of this PR with matplotlib>=3.5.3 should be good to go then.

**Review by ReimarBauer — APPROVED** [review]

**Pull request merged**
