### PR TITLE
improved mscolab tests

### LINKED ISSUE #963: refactor seed based tests
we want to remove seed data for mscolab testing purpose and initial all tests itselfs. This improves independency of tests.

### PR DESCRIPTION
**Pull request by ReimarBauer**

### CODE REVIEW

**Comment by Marilyth** [comment]
Are you still going to solve the tearDown in this PR? I feel unsure to approve it in case you still have plans to fix the socket manager tests.

**Comment by ReimarBauer** [comment]
I am trying this out a little further 

found out a few new things.

**Comment by ReimarBauer** [comment]
beautifying will be a seperate PR, finished for now.

**Review by joernu76 — APPROVED** [review]

**Comment by joernu76** [comment]
I would suggest to put the port ranges into a _test utility modules. A function like
```
PORTS = ....get_port_range(__file__)
```
With a hard coded dictionary assigning ranges to files (cutting everything before "mslib/"). Reviewing if a range is given twice is a tad cumbersome in the long run.
Hard-coded because I am not sure how to create a "dynamic" distribution that behaves identically over multiple-processes and python versions.

**Pull request merged**
