### PR TITLE
Rename 'create' parameter in 'demodata' to 'seed'

### LINKED ISSUE #653: unify parameter for creation of demodata to "seed"
We have two server components which can be tried with some demodata.

```
python mslib/mswms/demodata.py --create

python mslib/mscolab/mscolab.py db --seed
```

In the demodata module "create" needs to become renamed to "seed". 

Documentations have to become updated too.

### PR DESCRIPTION
**Pull request by jerinjtitus**
Signed-off-by: Jerin J Titus <72017981+jerinjtitus@users.noreply.github.com>

Fixes #653.

### CODE REVIEW

**Review by ReimarBauer — DISMISSED** [review]
Thx

**Comment by ReimarBauer** [comment]
A merge of this impacts our setup of dockerhub for the development branch.  
https://github.com/Open-MSS/dockerhub/blob/develop/script.sh#L10

And we have to update short afterwards the development instructions
https://github.com/Open-MSS/Open-MSS.github.io/blob/gh-pages/docs/develop/Setup-Instructions.md

**Review by Marilyth — CHANGES_REQUESTED** [review]
https://github.com/Open-MSS/MSS/blob/21a8e867615ceabf91ad7a254586249f64f84e64/mslib/mswms/demodata.py#L1209
This line needs to be changed to reflect the changes.

**Review by Marilyth — APPROVED** [review]

**Review by ReimarBauer — APPROVED** [review]
ok, merge order, this at first. ~15 min later the testing framework PR.

**Pull request merged**
