### PR TITLE
Added option to display a secondary axis in SideView.

### LINKED ISSUE #571: Allow Vertical Plots to have Secondary Y-Axis
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/571) by Shawn Honomichl (Bitbucket: [Shawn](https://bitbucket.org/Shawn), GitHub: [Shawn](https://github.com/Shawn)).**

----------------------------------------

It would be useful to have in the Side View Options menu, an option to add a secondary y-axis on the right side of the plot.  For example, if the menu is set to have ‘flight level’ as the primary y-axis value,  the secondary y-axis could be pressure or pressure altitude.

### LINKED ISSUE #581: test_sideview needs a review
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/581) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

test\_sideview needs a review. Sometimes this happens

```
mslib/msui/_tests/test_sideview.py:180: AssertionError
 * Serving Flask app "mslib.index" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
PASSED [ 55%] * Serving Flask app "mslib.index" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
PASSED [ 55%]SKIPPED                         [ 55%]
Skipped: file(s) previously passed FLAKE8 checks
PASSED [ 56%]Traceback (most recent call last):
  File "/home/user/PycharmProjects/mss/mslib/msui/sideview.py", line 239, in verticalunitsclicked
    thermolib.pressure2flightlevel(self.sbPbot.value() * 100), "hft", unit))
  File "/home/user/PycharmProjects/mss/mslib/thermolib.py", line 850, in pressure2flightlevel
    raise ValueError("pressure to flight level conversion not "
ValueError: pressure to flight level conversion not implemented for z > 71km (p ~ 4 Pa)
```

‌

### PR DESCRIPTION
**Pull request by joernu76**
Fix #571

### CODE REVIEW

**Review by Marilyth — DISMISSED** [review]

**Comment by jgrooss** [comment]
How do I download and install this branch issue571?

**Comment by joernu76** [comment]
@jgrooss If you have cloned the repo here already simply by "git fetch origin" and "git checkout origin/issue571"
To not have the scary looking warning use "git checkout origin/issue571 -b issue571".

**Comment by jgrooss** [comment]
The right axis labels are not visible in my example
sideview_Temperature

**Review by jgrooss — DISMISSED** [review]
In the case I showed in the comment above the axis labels did overlap with the figure. This needs to be solved first.

**Comment by ReimarBauer** [comment]
@jgrooss I don't have that problem. Which matplotlib version do you use?

**Comment by jgrooss** [comment]
I used the mssenv from version 3.0.2 and had to install skyfield-data. ant then did run manually by
PYTHONPATH=. python mslib/msui/mss_pyui.py
Any more things to be installed updated?

**Comment by ReimarBauer** [comment]
In the mssenv there is usually mss installed. when you want to have only the development version of code you need to `mamba remove mss --force` 

This is how it looks for me

sideview_Specific

Indeed "lat/lon" is not written on bottom of the time axis. But the second axis looks good to me

If I resized vertically my widget then "lat/lon" is also added on bottom.

scnd_sideview_Relative

**Comment by ReimarBauer** [comment]
if you want to update mss
I do usually. I also look on the list if it has 3.0.4 ;)
```
mamba update mss
mamba update --all
```
I have
```
matplotlib                3.4.2            py39hf3d152e_0    conda-forge
matplotlib-base           3.4.2            py39h2fa2bec_0    conda-forge
```

**Comment by joernu76** [comment]
I'll have a look if I see something that might cause the issue.

**Comment by joernu76** [comment]
There was a bug related to the instantiation of the axis. The imgaxis did not rescale properly.
I also fixed an unrelated bug, which required a reload of the map whenever a different vertical axistype but pressure was used.

**Review by jgrooss — DISMISSED** [review]
Now it looks good for my case

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
I'm not sure when the unit of the vertical extend should change. currently it does only after "Ok"

a bigger problem, Fatal Error

Selected on both axes pressure altitude

```
Fatal error in MSS 3.0.3. on Linux-4.15.0-143-generic-x86_64-with-glibc2.27
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/2021/tmp/MSS/mslib/msui/sideview.py", line 333, in set_options
    self.getView().set_settings(settings)
  File "/home/user/PycharmProjects/2021/tmp/MSS/mslib/msui/mpl_qtwidget.py", line 762, in set_settings
    self.update_vertical_extent_from_settings()
  File "/home/user/PycharmProjects/2021/tmp/MSS/mslib/msui/mpl_qtwidget.py", line 837, in update_vertical_extent_from_settings
    self.p_bot = thermolib.flightlevel2pressure(self.settings_dict["vertical_extent"][0] * 32.80)
  File "/home/user/PycharmProjects/2021/tmp/MSS/mslib/thermolib.py", line 827, in flightlevel2pressure
    raise ValueError("flight level to pressure conversion not "
ValueError: flight level to pressure conversion not implemented for z > 71km
```

**Comment by joernu76** [comment]
> I'm not sure when the unit of the vertical extend should change. currently it does only after "Ok"
This is a blocking dialogue. So the behaviour is intended and fine.

> Selected on both axes pressure altitude
> 
> ```
> Fatal error in MSS 3.0.3. on Linux-4.15.0-143-generic-x86_64-with-glibc2.27
> Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
> [GCC 9.3.0]
> 
> Please report bugs in MSS to https://github.com/Open-MSS/MSS
> 
> Information about the fatal error:
> 
> Traceback (most recent call last):
>   File "/home/user/PycharmProjects/2021/tmp/MSS/mslib/msui/sideview.py", line 333, in set_options
>     self.getView().set_settings(settings)
>   File "/home/user/PycharmProjects/2021/tmp/MSS/mslib/msui/mpl_qtwidget.py", line 762, in set_settings
>     self.update_vertical_extent_from_settings()
>   File "/home/user/PycharmProjects/2021/tmp/MSS/mslib/msui/mpl_qtwidget.py", line 837, in update_vertical_extent_from_settings
>     self.p_bot = thermolib.flightlevel2pressure(self.settings_dict["vertical_extent"][0] * 32.80)
>   File "/home/user/PycharmProjects/2021/tmp/MSS/mslib/thermolib.py", line 827, in flightlevel2pressure
>     raise ValueError("flight level to pressure conversion not "
> ValueError: flight level to pressure conversion not implemented for z > 71km
> ```

That is almost certainly not new. I remember seeing that  but couldn't reproduce it. I'll see if I can fix that as well.

**Comment by ReimarBauer** [comment]
it is difficult to reproduce, may happen rare
https://github.com/Open-MSS/MSS/issues/581

**Comment by joernu76** [comment]
Fixed a long-standing bug. the unit-limits were only updated when the *mouse* was used to change the primary axis type. Keyboard changes were disregarded, which caused *very* wrong values to be used as limits. Thus the fatal error.
Now the code is properly connected and also a bit cleaner than before.

**Review by ReimarBauer — APPROVED** [review]
thx

**Pull request merged**
