### PR TITLE
[WIP] Disconnect button replaced #639

### LINKED ISSUE #639: mscolab disconnect button
The disconnect button should use the position of the connect button after  connected. And with disconnect the button should show connect.

disconnect

There are changes in mscolab.py needed
https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/mscolab.py

### PR DESCRIPTION
**Pull request by ahelii16**

### CODE REVIEW

**Comment by ReimarBauer** [comment]
HI @Ahelii16 if you want a little help, please ask on our channel.

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
please fix the merge conflicts

**Comment by ahelii16** [comment]
@ReimarBauer the merge conflicts now arising are the ones where I have changed the connectMscolab to toggleConnectionBtn

**Comment by ReimarBauer** [comment]
> @ReimarBauer the merge conflicts now arising are the ones where I have changed the connectMscolab to toggleConnectionBtn

@Ahelii16 you know your changes best, you need to select the changes you did. The differences are the reason that we can't automatically merge that. Merging means in that case deciding which lines to acceppt.

**Comment by ahelii16** [comment]
@ReimarBauer test_mscolab.py is failing after I made the changes. In every function with the line: assert self.window.label.text() == 'Welcome, berta'

**Comment by ahelii16** [comment]
__________________________________________ Test_Mscolab.test_user_delete ___________________________________________

self = <test_mscolab.Test_Mscolab object at 0x7f233263e9a0>
mockmessage = <MagicMock name='question' id='139789147091968'>

    @mock.patch("PyQt5.QtWidgets.QMessageBox.question", return_value=QtWidgets.QMessageBox.Yes)
    def test_user_delete(self, mockmessage):
        self._connect_to_mscolab()
        self._create_user("something", "something@something.org", "something")
        self._login("something@something.org", "something")
>       u_id = self.window.user['id']
E       AttributeError: 'MSSMscolabWindow' object has no attribute 'user'

mslib/msui/_tests/test_mscolab.py:197: AttributeError
---------------------------------------------- Captured stdout setup -----------------------------------------------
Database seeded successfully!
_______________________________________ Test_Mscolab.test_set_exported_file ________________________________________

self = <test_mscolab.Test_Mscolab object at 0x7f23326db8e0>
mockopen = <MagicMock name='get_open_filename' id='139789145746832'>
mockmessage = <MagicMock name='showMessage' id='139789145116000'>

    @mock.patch("mslib.msui.mscolab.QtWidgets.QErrorMessage.showMessage")
    @mock.patch("mslib.msui.mscolab.get_open_filename", return_value=os.path.join(sample_path, u"example.ftml"))
    def test_set_exported_file(self, mockopen, mockmessage):
        # name is misleading
        self._connect_to_mscolab()
        self._create_user("something", "something@something.org", "something")
        self._login("something@something.org", "something")
        assert self.window.listProjects.model().rowCount() == 0
        QtTest.QTest.mouseClick(self.window.addProject, QtCore.Qt.LeftButton)
        QtWidgets.QApplication.processEvents()
>       self.window.add_proj_dialog.path.setText(str("example"))
E       AttributeError: 'MSSMscolabWindow' object has no attribute 'add_proj_dialog'

mslib/msui/_tests/test_mscolab.py:222: AttributeError
---------------------------------------------- Captured stdout setup -----------------------------------------------
Database seeded successfully!
__________________________________________ Test_Mscolab.test_add_project ___________________________________________

self = <test_mscolab.Test_Mscolab object at 0x7f23326e4460>

    def test_add_project(self):
        # ToDo testneeds to be independent from test_user_delete
        self._connect_to_mscolab()
        self._create_user("something", "something@something.org", "something")
        self._login("something@something.org", "something")
>       assert self.window.label.text() == 'Welcome, something'
E       AssertionError: assert 'TextLabel' == 'Welcome, something'
E         - Welcome, something
E         + TextLabel

mslib/msui/_tests/test_mscolab.py:238: AssertionError
---------------------------------------------- Captured stdout setup -----------------------------------------------
Database seeded successfully!
____________________________________________ Test_Mscolab.test_add_user ____________________________________________

self = <test_mscolab.Test_Mscolab object at 0x7f233257d370>

    def test_add_user(self):
        self._connect_to_mscolab()
        self._create_user("something", "something@something.org", "something")
        self._login("something@something.org", "something")
        # screen shows logout button
>       assert self.window.label.text() == 'Welcome, something'
E       AssertionError: assert 'TextLabel' == 'Welcome, something'
E         - Welcome, something
E         + TextLabel

mslib/msui/_tests/test_mscolab.py:251: AssertionError
---------------------------------------------- Captured stdout setup -----------------------------------------------
Database seeded successfully!
_________________________________________ Test_Mscolab.test_get_recent_pid _________________________________________

self = <test_mscolab.Test_Mscolab object at 0x7f2332746190>

    def test_get_recent_pid(self):
        self._connect_to_mscolab()
        self._create_user("anton", "anton@something.org", "something")
        self._login("anton@something.org", "something")
>       assert self.window.label.text() == 'Welcome, anton'
E       AssertionError: assert 'TextLabel' == 'Welcome, anton'
E         - Welcome, anton
E         + TextLabel

mslib/msui/_tests/test_mscolab.py:295: AssertionError
---------------------------------------------- Captured stdout setup -----------------------------------------------
Database seeded successfully!
_______________________________________ Test_Mscolab.test_get_recent_project _______________________________________

self = <test_mscolab.Test_Mscolab object at 0x7f23325a2460>

    def test_get_recent_project(self):
        self._connect_to_mscolab()
        self._create_user("berta", "berta@something.org", "something")
        self._login("berta@something.org", "something")
>       assert self.window.label.text() == 'Welcome, berta'
E       AssertionError: assert 'TextLabel' == 'Welcome, berta'
E         - Welcome, berta
E         + TextLabel

mslib/msui/_tests/test_mscolab.py:309: AssertionError
---------------------------------------------- Captured stdout setup -----------------------------------------------
Database seeded successfully!
____________________________________ Test_Mscolab.test_delete_project_from_list ____________________________________

self = <test_mscolab.Test_Mscolab object at 0x7f233227c9d0>

    def test_delete_project_from_list(self):
        self._connect_to_mscolab()
        self._create_user("other", "other@something.org", "something")
        self._login("other@something.org", "something")
>       assert self.window.label.text() == 'Welcome, other'
E       AssertionError: assert 'TextLabel' == 'Welcome, other'
E         - Welcome, other
E         + TextLabel

mslib/msui/_tests/test_mscolab.py:340: AssertionError
---------------------------------------------- Captured stdout setup -----------------------------------------------

**Comment by ReimarBauer** [comment]
> @ReimarBauer test_mscolab.py is failing after I made the changes. In every function with the line: assert self.window.label.text() == 'Welcome, berta'

Hi @Ahelii16 
I tried the command line merge. 
Step 1: From your project repository, check out a new branch and test the changes.
```
git checkout -b Ahelii16-mscolab-disconnect-fix develop
git pull https://github.com/Ahelii16/MSS.git mscolab-disconnect-fix
```
Step 2: Merge the changes and update on GitHub.
```
git checkout develop
git merge --no-ff Ahelii16-mscolab-disconnect-fix
```

The line is missing 
https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/_tests/test_mscolab.py#L59

With adding that line tests run. 

I've also seen in my merge that in some tests the replacement check was not merged in.


The Web IDE seems to have L59 right.

**Comment by ReimarBauer** [comment]
I don't know why the merge has not these lines.  These are needed to show the window. This is helpful for seeing what happens. For executing the tests it is not needed. 

```
index 91c1c0fc..901702c4 100644
--- a/mslib/msui/_tests/test_mscolab.py
+++ b/mslib/msui/_tests/test_mscolab.py
@@ -61,6 +61,10 @@ class Test_Mscolab(object):
         self.application = QtWidgets.QApplication(sys.argv)
         self.window = MSSMscolabWindow(data_dir=mscolab_settings.MSCOLAB_DATA_DIR,
                                        mscolab_server_url=self.MSCOLAB_URL_TEST)
+        self.window.show()
+        QtWidgets.QApplication.processEvents()
+        QtTest.QTest.qWaitForWindowExposed(self.window)
+        QtWidgets.QApplication.processEvents()
 
     def teardown(self):
         QtTest.QTest.mouseClick(self.window.logoutButton, QtCore.Qt.LeftButton)
```

The tests are failing for those tests which do connect and afterwards login.
The login currently has also a self._connect_to_mscolab() which will do than the disconnect. 


This needs to be changed for the new situation ;)

e.g. remove the line there, add the _connect to the tests which have only a login

**Comment by ahelii16** [comment]
@ReimarBauer since I have made a new PR for this issue, should I close this one?

**Pull request closed without merging**
