### PR TITLE
Add workflow_dispatch trigger to enable manual stable tests

### LINKED ISSUE #2172: The scheduled test does not test stable properly
The scheduled test runs the workflow from develop with the code from develop, but with the container image for stable. This is wrong, it should run the workflow from stable with the code from stable and its corresponding container image instead.

This is not so trivial to fix, because scheduled workflows only run for the default branch. I think the most straight forward approach would be to use workflow_dispatch and trigger a workflow run on stable from a scheduled workflow on develop.

### PR DESCRIPTION
**Pull request by rohit2p**
**Purpose of PR?**:
This pull request builds upon my previous change in PR #2196 
I've added the `workflow_dispatch:` trigger to the `testing-stable.yml` file on the stable branch. This allows manual triggering of stable tests, improving testing flexibility and control.

Fixes #2172 

**Checklist:**
- [x] Bug fix. Fixes #2172

### CODE REVIEW

**Comment by rohit2p** [comment]
The error message I'm seeing is `Fatal Python error: Aborted`. I've checked the relevant code section but haven't been able to identify the issue.
Could you please help me understand what might be causing this failure and how to fix it?

**Comment by rohit2p** [comment]
not sure, but is it because any update  regarding the `actions/checkout` version
image

**Comment by matrss** [comment]
> The error message I'm seeing is `Fatal Python error: Aborted`. I've checked the relevant code section but haven't been able to identify the issue. Could you please help me understand what might be causing this failure and how to fix it?

This is happening on the stable branch already without this PR, and I don't know yet what is broken there. This PR certainly did not cause it.

> not sure, but is it because any update regarding the `actions/checkout` version image

This warning is also unrelated to this PR, the actions/checkout version needs to be updated.

**Review by matrss — APPROVED** [review]
LGTM

**Comment by rohit2p** [comment]
Thanks for your comment. Please let me know if you need anything further from me.

**Comment by ReimarBauer** [comment]
Hmm, ideas why we now have these coredumps?

**Comment by matrss** [comment]
@ReimarBauer they are happening on the stable branch already, e.g. here: https://github.com/Open-MSS/MSS/actions/runs/7854540812/job/21569532674. So that is unrelated to this PR. I am very much sure that it is because of the missing pyvirtualdisplay/xvfb-run. The issue for that is here: #2199.

**Comment by ReimarBauer** [comment]
> @ReimarBauer they are happening on the stable branch already, e.g. here: https://github.com/Open-MSS/MSS/actions/runs/7854540812/job/21569532674. So that is unrelated to this PR. I am very much sure that it is because of the missing pyvirtualdisplay/xvfb-run. The issue for that is here: #2199.

ok, this fix must then be first merged then we can recheck this one. With "repeating" failing tests other merge requests will be more difficult to merge.

**Comment by matrss** [comment]
In general I'd agree, but this PR is literally a single line change that makes the workflow manually start-able, nothing else.

Slightly OT: the stable/develop split makes it so that failures on stable (i.e. the non-default branch of the two) are not as easily visible, since they show up nowhere on the repo landing page. I don't like that. Also, the change that broke the CI happened in a different repository. I also don't like that that is possible.

Anyway, I'll send a fix for the broken CI.

**Pull request merged**
