### PR TITLE
Merge Stable into develop

### PR DESCRIPTION
**Pull request by ReimarBauer**

### CODE REVIEW

**Review by Marilyth — APPROVED** [review]
Looks fine.

**Comment by ReimarBauer** [comment]
Don't click on, Don't Don't Don't !!

never

**Comment by joernu76** [comment]
This requires a IMO a rebase to be mergable. As we cannot rebase stable, we need to fork stable, rebase it onto develop and then merge it.
merging develop into stable should work similarily.
I need to think about how much sense a semi-linear history has for a two-branch development, though.
Also, the update branch button is not-clickable due to my restriction on semi-linear history.

**Comment by ReimarBauer** [comment]
has been done by rebasing as suggested

**Pull request closed without merging**
