### PR TITLE
Merge develop to stable == 9.0.0

### PR DESCRIPTION
**Pull request by ReimarBauer**
**Purpose of PR?**:

this is the base of the next stable release 9.x

388 files changed, 13933 insertions(+), 8041 deletions(-)

There was no merge conflict.

Removed the pyvirtualdisplay section from testing.yml

This needs a **merge**.

### CODE REVIEW

**Comment by ReimarBauer** [comment]
```
git diff develop

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
index b6e7d33c..0e1f739f 100644
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -31,13 +31,6 @@ jobs:
       run: cmp -s /meta.yaml localbuild/meta.yaml && cmp -s /development.txt requirements.d/development.txt ||
         (echo Dependencies differ && echo "triggerdockerbuild=yes" >> $GITHUB_ENV )
 
-    - name: Install pyvirtualdisplay if on stable
-      if: ${{ inputs.image_suffix == 'stable' }}
-      run: |
-        source /opt/conda/etc/profile.d/conda.sh
-        source /opt/conda/etc/profile.d/mamba.sh
-        mamba install -n mss-${{ inputs.image_suffix }}-env pyvirtualdisplay
-
     - name: Always rebuild dependencies for scheduled builds (started from testing-scheduled.yml)
       if: ${{ github.event_name == 'workflow_dispatch' }}
       run: echo "triggerdockerbuild=yes" >> $GITHUB_ENV
```

**Comment by ReimarBauer** [comment]
@matrss I wonder why we don't see a coverage.

**Comment by matrss** [comment]
> @matrss I wonder why we don't see a coverage.

Coveralls shows it as "pending completion", no idea why. See: https://coveralls.io/builds/67629652

**Comment by ReimarBauer** [comment]
> > @matrss I wonder why we don't see a coverage.
> 
> Coveralls shows it as "pending completion", no idea why. See: https://coveralls.io/builds/67629652

Then we ignore it that time, perhaps it had a network hickup.

**Review by matrss — APPROVED** [review]
Same as develop modulo the pyvirtualdisplay step, and CI passes. So, LGTM.

**Review by joernu76 — APPROVED** [review]

**Pull request merged**
