### PR TITLE
Added instructions for gh command

### LINKED ISSUE #1587: update documentation for gh command
github has a new cli command for cloning etc.

https://github.com/cli/cli/blob/trunk/docs/install_linux.md

### PR DESCRIPTION
**Pull request by rootxrishabh**
fixes #1587 

As gh is the new command for cloning on GitHub, added instructions to docs.

### CODE REVIEW

**Comment by ReimarBauer** [comment]
@rootxrishabh please sync this with develop branch

**Comment by ReimarBauer** [comment]
in_your_fork

**Comment by rootxrishabh** [comment]
@ReimarBauer I have synced the branch please check

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
tried the example

gh repo clone ReimarBauer/MSS.git
GraphQL: Could not resolve to a Repository with the name 'ReimarBauer/MSS.git'. (repository)

likly a copy/paste failure.

**Comment by rootxrishabh** [comment]
@ReimarBauer try testing now

**Review by ReimarBauer — APPROVED** [review]
Thx

**Comment by rootxrishabh** [comment]
Thank you for helping out.

**Pull request merged**
