### PR TITLE
Tests refactored - new action for pytest-xdist for a selection of tests

### LINKED ISSUE #530: review tests and maybe refactor for pytest parallel
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/530) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

We may be can use multiple workers for pytest

[https://pypi.org/project/pytest-parallel/](https://pypi.org/project/pytest-parallel/)

We have to carefully check how we have to change our tests.  

multi threading likly won’t be possible.

‌

### LINKED ISSUE #680: Test_mscolab.py failing in develop branch
Failing in:  test_view_open, test_get_recent_pid

### LINKED ISSUE #681: refactoring of mscolab tests
the mscolab tests needs a refactoring for faster execution, if possible executed by pytest-xdist.
This is not mandatory. A first step is to setup a framework that generates users and data on the fly and start fresh for each test to remove dependency.

By my (Reimar) current refactoring based on the existing tools I'm not sure if it ever will work perfect with xdist. But trying with that also shows parts to improve.

### PR DESCRIPTION
**Pull request by ReimarBauer**
removed some Inherited dependencies
enabled wms tests to get parallel executed

### CODE REVIEW

**Comment by ReimarBauer** [comment]
mscolab tests currently can´t be run by pytest-xdist. A seperation by a keyword for the wms tests shows the speedup

## test output on screeen

pytest -k wms 

126 passed, 3 skipped, 259 deselected, 44 warnings in 231.91s (0:03:51)


pytest -n 6 --dist loadfile  --max-worker-restart 0 -k wms

126 passed, 3 skipped, 50 warnings in 146.11s (0:02:26)


pytest -n 6 --dist loadscope  --max-worker-restart 0 -k wms

126 passed, 3 skipped, 50 warnings in 141.52s (0:02:21)


## testoutput on pyvirtualdisplay

pytest -k wms

126 passed, 3 skipped, 259 deselected, 44 warnings in 228.22s (0:03:48)


pytest -n 6 --dist loadfile  --max-worker-restart 0 -k wms

126 passed, 3 skipped, 50 warnings in 147.11s (0:02:27)


pytest -n 6 --dist loadscope  --max-worker-restart 0 -k wms

126 passed, 3 skipped, 50 warnings in 140.51s (0:02:20)

pytest -n 3 --dist loadscope  --max-worker-restart 0 -k wms

126 passed, 3 skipped, 47 warnings in 135.41s (0:02:15)

pytest -n 2 --dist loadscope  --max-worker-restart 0 -k wms

126 passed, 3 skipped, 46 warnings in 148.82s (0:02:28)


### everything without mscolab
pytest  -v -n 4 --dist loadscope  --max-worker-restart 0  --ignore  ./mslib/msui/_tests/test_mscolab_admin_window.py --ignore ./mslib/msui/_tests/test_mscolab.py --ignore ./mslib/msui/_tests/test_mscolab_version_history.py --ignore ./mslib/msui/_tests/test_mscolab_merge_waypoints.py --ignore ./mslib/msui/_tests/test_mscolab_project.py  --ignore ./mslib/mscolab/_tests/test_user.py --ignore ./mslib/mscolab/_tests/test_files.py --ignore ./mslib/mscolab/_tests/test_server.py --ignore ./mslib/mscolab/_tests/test_utils.py --ignore ./mslib/mscolab/_tests/test_files_api.py --ignore ./mslib/mscolab/_tests/test_chat_manager.py --ignore ./mslib/mscolab/_tests/test_sockets.py --ignore ./mslib/mscolab/_tests/test_file_manager.py --ignore ./mslib/mscolab/_tests/test_chat.py 

231 passed, 6 skipped, 2190 warnings in 141.92s (0:02:21)

#### duration more than 5 seconds each


40.02s call     mslib/msui/_tests/test_topview.py::Test_MSSTopViewWindow::test_open_rs
16.33s call     mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_server_getmap_cached
12.53s call     mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_server_getmap
9.54s call     mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_server_abort_getmap
8.53s call     mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_server_service_cache
7.35s setup    mslib/_tests/test_netCDF4tools.py::Test_netCDF4tools::test_identify_variable
7.32s setup    mslib/_tests/test_index.py::test_xstatic
7.28s setup    mslib/_tests/test_convert.py::test_convert_to
7.25s setup    mslib/_tests/test_thermolib.py::test_flightlevel2pressure
7.04s call     mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_no_server
7.02s call     mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_invalid_url
7.01s call     mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_no_schema
7.01s call     mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_invalid_schema
5.07s setup    mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_no_schema
5.07s setup    mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_server_service_cache
5.06s setup    mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_server_getmap_cached
5.06s setup    mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_no_server
5.05s setup    mslib/msui/_tests/test_wms_control.py::Test_VSecWMSControlWidget::test_server_getmap
5.04s setup    mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_invalid_schema
5.03s setup    mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_server_abort_getmap
5.03s setup    mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_connection_error
5.03s setup    mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_server_getmap
5.02s setup    mslib/msui/_tests/test_wms_control.py::Test_HSecWMSControlWidget::test_invalid_url


### mscolab tests

 pytest -v  --dist no  --max-worker-restart 0  -k mscolab  --durations=0 

58 passed, 5 skipped, 325 deselected, 406 warnings in 459.00s (0:07:38)

#### duration more than 5 seconds each

16.21s call     mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_refresh
12.17s call     mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_changes
11.29s setup    mslib/msui/_tests/test_mscolab.py::Test_Mscolab::test_url_combo
10.24s call     mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_undo
10.11s call     mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_set_version_name
6.85s call     mslib/msui/_tests/test_mscolab.py::Test_Mscolab::test_work_locally_toggle
6.08s call     mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_version_name_delete
5.44s setup    mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_version_name_delete
5.42s setup    mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_refresh
5.41s setup    mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_set_version_name
5.40s setup    mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_version_name_filter
5.39s setup    mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_changes
5.38s setup    mslib/msui/_tests/test_mscolab_version_history.py::Test_MscolabVersionHistory::test_undo

## next steps
- check which mscolab tests can be already run by xdist. The expensest one may be can be run  --dist loadfile 

may be  all tests of mscolab  have to be changed to have a mscolab in its name, the -k does only select on name not on dir. the next example misses all tests below mslib/mscolab
* pytest -v --dist no --max-worker-restart 0 -k mscolab --durations=0 --ignore ./mslib/msui/_tests/test_mscolab.py
 19 passed, 4 skipped, 325 deselected, 338 warnings in 147.44s (0:02:27)

*  pytest -v -n 4 --dist loadfile --max-worker-restart 0 --ignore ./mslib/msui/_tests/test_mscolab_admin_window.py --ignore ./mslib/msui/_tests/test_mscolab_version_history.py --ignore ./mslib/msui/_tests/test_mscolab_merge_waypoints.py --ignore ./mslib/msui/_tests/test_mscolab_project.py --ignore ./mslib/mscolab/_tests/test_user.py --ignore ./mslib/mscolab/_tests/test_files.py --ignore ./mslib/mscolab/_tests/test_server.py --ignore ./mslib/mscolab/_tests/test_utils.py --ignore ./mslib/mscolab/_tests/test_files_api.py --ignore ./mslib/mscolab/_tests/test_chat_manager.py --ignore ./mslib/mscolab/_tests/test_sockets.py --ignore ./mslib/mscolab/_tests/test_file_manager.py --ignore ./mslib/mscolab/_tests/test_chat.py

270 passed, 7 skipped, 2258 warnings in 355.97s (0:05:55)

**Comment by ReimarBauer** [comment]
Selected-MSS-Tests needs a new module in develoment requirements.d which is only after the merge there.

**Comment by ReimarBauer** [comment]
After this is merged a next step is https://github.com/Open-MSS/MSS/issues/681

**Comment by Marilyth** [comment]
> Selected-MSS-Tests needs a new module in develoment requirements.d which is only after the merge there.

I can confirm the job passes on GitHub with pytest-xdist installed.

**Review by joernu76 — APPROVED** [review]
I do not fully understand the current build process, but the changes look okay.

**Pull request merged**
