### PR TITLE
Fix focus-stealing

### LINKED ISSUE #2020: develop: typing in password in MSColab login steals focus

### PR DESCRIPTION
**Pull request by joernu76**
* add proper auto-default and focus of buttons

Fixes #2020

**Purpose of PR?**:

Fixes #2020

**Does this PR introduce a breaking change?**
no

### CODE REVIEW

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
there is one more focus too much 
blinking_cursor

I would expect when everythings gets preconfigured not to have a cursor in the "server url" field.

The user should have to click there to change it.

I get to this on first connect, when disconnect directly it behaves as expected

**Comment by joernu76** [comment]
True. Is fixed now. The setAutoDefault has been moved to the ui file. I added setAutoDefault for good measure to the connect button on the MainMenu.

The setFocus commands remain necessary, due to the activation of text fields by setting text in them.

**Comment by ReimarBauer** [comment]
great, the first Connect has now also that feature :)

**Review by ReimarBauer — APPROVED** [review]
Thx

**Pull request merged**
