### PR TITLE
fix: the flake8 max line failure

### LINKED ISSUE #2111: python-flake8 max-line-length failure
The setup.cfg defines a max-line-length = 120 and this is overwritten in the python-flake8 with 127.

The extra definition in the worker script should be removed so that the settings from setup.cfg are used

### PR DESCRIPTION
**Pull request by rohit2p**
**Purpose of PR?**:

Fixes #2111

**Checklist:**
- [X] Bug fix. Fixes #2111 

**I removed the max-line-length = 127 from the python-flake8 because it was overwriting setup.cfg. These changes ensure that the codebase adheres to the project's coding standards and resolves the reported issues.**

### CODE REVIEW

**Comment by ReimarBauer** [comment]
@rohit2p now I know what you meant by  the E501, E501 line too long (121 > 120 characters)

Yes you were right this needs to be fixed too. Sorry for the confusement,.

**Comment by rohit2p** [comment]
@ReimarBauer yes and we can fix this by doing this 
image

**Comment by ReimarBauer** [comment]
> @ReimarBauer yes and we can fix this by doing this image

This fixes the wrong file. 

Please read the test output

https://github.com/Open-MSS/MSS/actions/runs/7432836388/job/20260097058?pr=2134

**Comment by rohit2p** [comment]
ok sorry i got confused because this same error is also present in conf.py
now according to the current error if we replace this code at line 571

```
  except (AttributeError, IOError, TypeError, et.XMLSyntaxError, et.XMLSchemaError, et.XMLSchemaParseError,
                        et.XMLSchemaValidateError) as ex:  # catches KML Syntax Errors        
```     
with this 

```
 except (AttributeError, IOError, TypeError, et.XMLSyntaxError, et.XMLSchemaError,
        et.XMLSchemaParseError, et.XMLSchemaValidateError) as ex:  # catches KML Syntax Errors
```
then this particular error will be fixed

**Comment by ReimarBauer** [comment]
try, we will see what the CI says ;)

**Comment by rohit2p** [comment]
does this work @ReimarBauer

**Comment by ReimarBauer** [comment]
@rohit2p look at the test output

**Comment by ReimarBauer** [comment]
maybe you need to configure vscode to remove trailing whitespaces? Doesn't it have a builtin flake8 checker?

**Comment by rohit2p** [comment]
i configured it thankyou. i think its fixed now.
btw what about the flake8 typos in the conf.py

**Comment by ReimarBauer** [comment]
They were automatically created by sphinx. 
And we don't check the docs. Not needed by now. This can become later a task when we work on the gallery feature.

**Comment by rohit2p** [comment]
@ReimarBauer so is everything good with this PR ?

**Comment by ReimarBauer** [comment]
triggered the tests, lets see

After the first successful merge, gh does that without a request

**Review by ReimarBauer — APPROVED** [review]
Thx

**Comment by rohit2p** [comment]
Thanks for merging. i feel very good now

**Pull request merged**
