### PR TITLE
Refactor keyring

### LINKED ISSUE #1730: refactor usage of keyring
simplify several http-auth authentications

### PR DESCRIPTION
**Pull request by ReimarBauer**
closes #1730

### CODE REVIEW

**Comment by joernu76** [comment]
I think, we should have some kind of backwards-compatibility in the next version, i.e. something like a check on both (old and new) entries, perhaps with a warning in case data is found in the old that you can click away once per start?

**Comment by ReimarBauer** [comment]
We likly need a kind of migration script. I do include this

**Comment by ReimarBauer** [comment]
@joernu76 the new test and the migration is version dependent. We could maybe merge the release preparation PR.

**Comment by ReimarBauer** [comment]
When it recognizes an old configuration it shows
message

**Comment by ReimarBauer** [comment]
the documentation is rendered like this
rendered_docs

**Review by joernu76 — APPROVED** [review]

**Pull request merged**
