### PR TITLE
Hide mscolab ui when not needed

### LINKED ISSUE #1625: MSColab UI should only be displayed when necessary
The MSColab interface for working with operations consumes a great deal of space of the main window, but is only needed when one connects to an MSCOlab server.

It would be desirable to hide this part until one connects to a server and rehides it upon disconnection.

### PR DESCRIPTION
**Pull request by joernu76**

### CODE REVIEW

**Review by ReimarBauer — COMMENTED** [review]
nice idea :)

have a look if the operation menu entry can be also disabled, removing may dissort the UI

**Comment by ReimarBauer** [comment]
@joernu76 please link with an issue (create that too)

**Comment by joernu76** [comment]
I juggled the other UI elements around a bit. Seems a bit more consistent now.
The MSColab connectivity has a permanent group box above with a more consistent status message.
I move the operation description to the MSCOlab operations box.

**Comment by joernu76** [comment]
I am not convinced that people will find the "disconnect" button. Toggling the connect button to disconnect'd be more intuitive, I think.
Web services try to make disconnecting/signing out purposely difficult; I am not sure we should follow that particular UI design philosophy, but that'd be a change for a different MR.

**Comment by ReimarBauer** [comment]
currently I like how it is, a lot web services have the logout feature in that position.  
Closing is also a logout, I guess when we would have something similar as closing the operation list, it may be an compromise. 
I look on the other changes after the it-forum ;)

**Comment by joernu76** [comment]
> currently I like how it is, a lot web services have the logout feature in that position. Closing is also a logout, I guess when we would have something similar as closing the operation list, it may be an compromise. I look on the other changes after the it-forum ;)

Currently, I did not change this.

**Comment by ReimarBauer** [comment]
Functionality so far ok, but I found something new in the UI which we hadn't before. It seems we can move things arround, somehow interesting but I think we don't have something to get into these elements yet?

unknown_element

When those are removed we would also save space.

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
there seems now a moveable toolbar in the UI see peek video. This can also be duplicated by the user.

I guess that got somehow in, and we don't have something to add there yet?

**Comment by joernu76** [comment]
Yes, there were *two* toolbars. I have no idea how they got added by qtcreator. I removed them. Should be fine now...

**Comment by ReimarBauer** [comment]
fun fact was that I somehow clicked on that and wondered what that is. Then I wanted to decribe this and needed long to figure that I have to click into the edge

**Review by ReimarBauer — APPROVED** [review]
Thx

**Pull request merged**
