### PR TITLE
Always return result and status_code

### LINKED ISSUE #1831: Usercreation broken
```
tail mscolab-error.log
Traceback (most recent call last):
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'user_register_handler' did not return a valid response. The function either returned None or ended without a return statement.
```

### PR DESCRIPTION
**Pull request by joernu76**
Fix #1831

### CODE REVIEW

**Comment by joernu76** [comment]
This fixes the issue at hand, but I am not sure that the logic is correct.

**Comment by ReimarBauer** [comment]
I patched that and it behaves correct. This should become simplified, too much included into the exception.

But I don't see why it is not mailing

**Comment by ReimarBauer** [comment]
Oh it is mailing but not to all receipents. That is a different problem.

**Comment by ReimarBauer** [comment]
The mailing issue is a naming conflict in postfix, I got a workaround for now

**Review by ReimarBauer — APPROVED** [review]
Thx

**Pull request merged**
