### PR TITLE
Proper disabling of unticked KML files.

### LINKED ISSUE #1866: tick/untick for multiple kml overlays does not work
if multiple kml overlay files are chosen, on can tick and untick the display of those. If one of two kml files is un-ticked it is anyhow displayed on refreshing the top view. 
The display can be stopped if the tick box is hit twice then (tic, untick

This is not how it should be

### PR DESCRIPTION
**Pull request by joernu76**
Fix #1866

### CODE REVIEW

**Comment by jgrooss** [comment]
This seems to work. At least I don't see the problem anymore

**Review by jgrooss — DISMISSED** [review]
This seems to have solved the problem

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
there is another problem, not checked if it is a new one.

When you click on change color on a not check marked kml it crashes.
Same with resize. 

change_color_problem

**Comment by joernu76** [comment]
will have a look

**Review by ReimarBauer — APPROVED** [review]
Thx

**Pull request merged**
