### PR TITLE
fix:Further refactoring to simplify control flow

### LINKED ISSUE #2514: unhandled crashes with mscolab verification shenanigangs
Using the "verify-user-token" feature causes unexpected behaviour. it is suggested to disable this by default as a quick fix.

One error:

```test_authorized
ERROR: unexpected error: <class 'requests.exceptions.MissingSchema'> Invalid URL 'test_authorized': No scheme supplied. Perhaps you meant https://test_authorized?
```
looses the server URL in checking after an unsuccessful login attempt.

Another one

```
Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 1788, in set_active_op_id
    item.setFont(font)
RuntimeError: wrapped C/C++ object of type QListWidgetItem has been deleted
2024-09-07 19:05:40,314 (qt.excepthook:183): CRITICAL: MSS Version: 9.2.0
2024-09-07 19:05:40,315 (qt.excepthook:184): CRITICAL: Python Version: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
2024-09-07 19:05:40,323 (qt.excepthook:185): CRITICAL: Platform: Linux-6.10.6+bpo-amd64-x86_64-with-glibc2.36 (('64bit', 'ELF'))
2024-09-07 19:05:40,323 (qt.excepthook:186): CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 1788, in set_active_op_id
    item.setFont(font)
RuntimeError: wrapped C/C++ object of type QListWidgetItem has been deleted

Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 1735, in set_active_op_id
    logging.debug('set_active_op_id %s %s %s', item, item.op_id, self.active_op_id)
AttributeError: 'QListWidgetItem' object has no attribute 'op_id'
```
causes QT related crashes upon the forced logging out, which apparently doesn't clean up properly.

Also restarting the mscolab server (which triggers an unexpected logging out) causes several issues preventing MSUI from being properly used.

### PR DESCRIPTION
**Pull request by joernu76**
Fewer LOC to make things more maintainable.
Also Fix #2514

**Purpose of PR?**:

Fixes #2514 

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Does this PR results in some Documentation changes?**
_If yes, include the list of Documentation changes_

**Checklist:**
- [x] Bug fix. Fixes #2514
- [ ] New feature (Non-API breaking changes that adds functionality)
- [ ] PR Title follows the convention of  `<type>: <subject>`
- [ ] Commit has unit tests

### CODE REVIEW

**Comment by joernu76** [comment]
The intent of this MR is again to enforce more consistent handling by use of decoration magic.

Several places had a pop_up messages saying that a new login was required without doing anything about this.
The new Exception shows consistently a popup message before triggering a logout.

The issue of #2521 was caused by a QT signal calling a MSColab function *after* logout, which caused a couple of issues.

The current code does not crash anymore on my end when the MSColab server is restarted. Now a test simulating server restarts and/or connection troubles would be next steps.

**Comment by joernu76** [comment]
Finally passes checks. As a change, the App now complains more often in case that the active operations was disabled with a popup. I believe this is sensible, but should be explored further in the next MR.

**Comment by joernu76** [comment]
So, for simplifying reviewing, hiding whitespace is essential.

1) The major change is the use of Exceptions to logout in a consistent manner in less code.
2) I try to properly set active_op_id to None, but this necessitated several changes in tests. I believe the behaviour is better now, but this is not over, yet.
3) I made QMessageBox and some minor QT stuff  consistent.

It passes testbench and several manual tests (certainly not all, but sensible stuff) on my computer behave in a clean, sensible fashion with two clients. Including restarting the server.

**Comment by ReimarBauer** [comment]
Thx @joernu76 I'll look at it later today.

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
Starting testing both cases


# connect - restart server - select
with the default to skip the verification it crashes. Using the client side verification not

## skip_verify True

skip_verify_connect_restart_select

## skip_verify False
no_skip_verify_connect_restart_select

**Comment by ReimarBauer** [comment]
# connect select restart select
with the default to skip the verification it crashes. Using the client side verification not

## skip_verify True
skip_verify_connect_select_restart_select



## skip_verify False
no_skip_verify_connect_select_restart_select

**Comment by ReimarBauer** [comment]
# connect select topview add restart add
with the default to skip the verification it crashes. Using the client side verification not
## skip_verify True
skip_verify_connect_select_topview_add_restart_add

## skip_verify False
no_skip_verify_connect_select_topview_add_restart_add

**Comment by ReimarBauer** [comment]
# connect select chat  restart message
with the default to skip the verification it does nothing. Using the client side verification it shows expired message

## skip_verify True
skip_verify_connect_select_chat_mnessage

## skip_verify False
no_skip_verify_connect_select_chat_mnessage

**Comment by joernu76** [comment]
So, two of these should be handled now in a general and robust fashion. I strongly dislike the "depth" counter, though Better ideas?
The CHAT is a separate class that I define as out-of-scope now. -> New issue.
@ReimarBauer

**Review by ReimarBauer — APPROVED** [review]
looks good.


I found another problem unrelated to these changes. A doubleclick on login gives a traceback and login works. 
That happens for both cases.

```
Fatal error in MSS 9.2.0 on Linux-6.11.0-100005-tuxedo-x86_64-with-glibc2.35
Python 3.11.10 | packaged by conda-forge | (main, Sep 10 2024, 11:01:28) [GCC 13.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 385, in login_handler
    self.mscolab.after_login(data["email"], self.mscolab_server_url, r)
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 694, in after_login
    self.connect_window.close()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
```

**Pull request merged**
