### PR TITLE
Fix broken remove/clear_figure link.

### LINKED ISSUE #1857: Linearview and Sideview crash on Clear figure by clicking on the remove button
In side view when pushing the button "remove", I get the following error:

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 709, in clear_map
    self.view.clear_figure()
AttributeError: 'MplSideViewCanvas' object has no attribute 'clear_figure'

### PR DESCRIPTION
**Pull request by joernu76**
Fix #1857

### CODE REVIEW

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
linearview needs a different implemention for clear_figure, see

remove_not_working

**Comment by joernu76** [comment]
This was a separate issue, but is now fixed as well.

**Comment by ReimarBauer** [comment]
There is a difference on clearing

On sideview the vertical line markers are kept. We keep also on topview the flightpath. So I think if that is not a tremdemous effort we should keep the vertical lines and coordinates, indicating the flightpath in linearview too.


difference_to_sv

**Comment by joernu76** [comment]
This is not easily possible as the lines are *not* stored as separate patches in contrast to the image in SideView. This requires refactoring beyond a stable fix. Please transfer this request to a new issue, which I will take care of in develop.

**Review by ReimarBauer — APPROVED** [review]
Thx

**Pull request merged**
