### PR TITLE
Allow GET requests to use query parameters

### LINKED ISSUE #1095: mscolab not JavaScript friendly
While developing the windy plugin I encountered a few oddities of mscolab which should be solved in order to be used with JavaScript.

1. API and Websocket don't return a CORS header, which is required for communication through JavaScript.
2. Some GET endpoints require request.form data. GET requests don't have a body, as such either query string request.args or the combined request.values should be used.

### PR DESCRIPTION
**Pull request by Marilyth**
fixes #1095 
GET requests normally don't have a body, as such it should have used `args`.
For backwards compatibility both should be allowed, and `args` should be preferred over `form`.
Werkzeug 2.0 removed the usability of `values` for GET requests.

### CODE REVIEW

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
please undo thes also to the new syntax
https://github.com/Open-MSS/MSS/commit/9a873bb0c5dadb2ac231c90c182c0c401056670f

create_project etc.

**Comment by Marilyth** [comment]
@ReimarBauer you want `request.form` of the POST requests to be converted to `request.values`?

**Comment by ReimarBauer** [comment]
> @ReimarBauer you want `request.form` of the POST requests to be converted to `request.values`?

In the past we had:
```
   path = request.values['path']
   description = request.values['description']
   content = request.values.get('content', None)
```

I changed this to
```
    path = request.form['path']
    content = request.form.get('content', None)
    description = request.form.get('description', None)
```
I'm currently undecided if I changed the behaviour or it was in the past wrong, what is your opinion?

**Comment by Marilyth** [comment]
Both behaviours are fine. It depends on if you even want query parameters to work for POST requests.
Sometimes they may contain sensitive information, sometimes the data would be too long for query parameters, etc.

Personally I would keep it the way it currently is. Forcing all information to be in the body for POST requests isn't bad, that's what POST requests are for.

**Review by ReimarBauer — APPROVED** [review]
Thx

**Pull request merged**
