### PR TITLE
Reworked KML overlay to take spherical geometry into account

### LINKED ISSUE #991: differences in kml visualizing of a flighpath to the path
seen on windows. used the new export of develop :)

mapping_problem

## ftml
```
<?xml version="1.0" encoding="utf-8"?>
  <FlightTrack version="3.0.4.">
    <ListOfWaypoints>
      <Waypoint flightlevel="250.0" lat="43.59040005634596" location="" lon="-4.001972108747712">
        <Comments></Comments>
      </Waypoint>
      <Waypoint flightlevel="250.0" lat="44.09751373432878" location="" lon="-2.417241865051416">
        <Comments></Comments>
      </Waypoint>
      <Waypoint flightlevel="250.0" lat="45.23851950979011" location="" lon="2.083392027046063">
        <Comments></Comments>
      </Waypoint>
      <Waypoint flightlevel="250.0" lat="45.49207634878152" location="" lon="4.935906465699393">
        <Comments></Comments>
      </Waypoint>
      <Waypoint flightlevel="250.0" lat="48.66153683617411" location="" lon="7.8518101141005765">
        <Comments></Comments>
      </Waypoint>
      <Waypoint flightlevel="250.0" lat="48.66153683617411" location="" lon="7.8518101141005765">
        <Comments></Comments>
      </Waypoint>
      <Waypoint flightlevel="250.0" lat="51.450662065079584" location="" lon="7.91519932384843">
        <Comments></Comments>
      </Waypoint>
      <Waypoint flightlevel="250.0" lat="51.450662065079584" location="" lon="7.91519932384843">
        <Comments></Comments>
      </Waypoint>
      <Waypoint flightlevel="250.0" lat="67.821" location="Kiruna" lon="20.336">
        <Comments></Comments>
      </Waypoint>
      <Waypoint flightlevel="250.0" lat="78.928" location="Ny-Alesund" lon="11.986">
        <Comments></Comments>
      </Waypoint>
    </ListOfWaypoints>
  </FlightTrack>
```

## kml

```
<?xml version="1.0" encoding="UTF-8" ?>
<kml xmlns="http://earth.google.com/kml/2.2">
<Document>
<name>dd</name>
<open>1</open>
<description>MSS flight track export</description>
<Style id="flighttrack">
<LineStyle><color>ff000000</color><width>4</width></LineStyle><PolyStyle><color>FFF87217</color></PolyStyle></Style>
<Placemark><name>dd</name>
<styleUrl>#flighttrack</styleUrl>
<LineString>
<tessellate>1</tessellate><altitudeMode>absolute</altitudeMode>
<coordinates>
-4.002,43.590,7620.000
-2.417,44.098,7620.000
2.083,45.239,7620.000
4.936,45.492,7620.000
7.852,48.662,7620.000
7.852,48.662,7620.000
7.915,51.451,7620.000
7.915,51.451,7620.000
20.336,67.821,7620.000
11.986,78.928,7620.000
</coordinates>
</LineString></Placemark>
</Document>
</kml>
```

### PR DESCRIPTION
**Pull request by joernu76**
Lines now follow shortest path on Earth's surface.
Minor flake8 fixes
Simplification of of great circle lines

### CODE REVIEW

**Comment by joernu76** [comment]
Performance of the whole KML is pretty abysmal. Need to look into that. The code doing the great circle interpolation is certainly not efficient, but if that is the problem needs to be investigated.

**Comment by joernu76** [comment]
Fix #991

**Comment by joernu76** [comment]
Somehow I cannot link the correct issue.?

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
I do try this soon. One wish already is to change the default linewidth from 5.0 to 2.0. 
https://github.com/Open-MSS/MSS/blob/f33ec5fcdc58b15609644e0512e82084861729c6/mslib/msui/kmloverlay_dockwidget.py#L486

**Comment by joernu76** [comment]
> I do try this soon. One wish already is to change the default linewidth from 5.0 to 2.0.
> 
> https://github.com/Open-MSS/MSS/blob/f33ec5fcdc58b15609644e0512e82084861729c6/mslib/msui/kmloverlay_dockwidget.py#L486



> I do try this soon. One wish already is to change the default linewidth from 5.0 to 2.0.
> 
> https://github.com/Open-MSS/MSS/blob/f33ec5fcdc58b15609644e0512e82084861729c6/mslib/msui/kmloverlay_dockwidget.py#L486

done

**Comment by ReimarBauer** [comment]
We don't have these quite large distances. I do see here a difference between point 8 connecting to western

edgecase
[onetrack.ftml.txt](https://github.com/Open-MSS/MSS/files/7216838/onetrack.ftml.txt)
[onetrack.kml.txt](https://github.com/Open-MSS/MSS/files/7216839/onetrack.kml.txt)

**Comment by joernu76** [comment]
> We don't have these quite large distances. I do see here a difference between point 8 connecting to western
> 
> edgecase
> [onetrack.ftml.txt](https://github.com/Open-MSS/MSS/files/7216838/onetrack.ftml.txt)
> [onetrack.kml.txt](https://github.com/Open-MSS/MSS/files/7216839/onetrack.kml.txt)

Interesting. Both paths are subject to the known issue, but why they show different artefacts is beyond me. I do not judge this to be a problem itself, but it may hint at an underlying one.

**Comment by ReimarBauer** [comment]
adding an other image to show how good this improvement is
triangle

**Comment by ReimarBauer** [comment]
> > We don't have these quite large distances. I do see here a difference between point 8 connecting to western
> > edgecase
> > [onetrack.ftml.txt](https://github.com/Open-MSS/MSS/files/7216838/onetrack.ftml.txt)
> > [onetrack.kml.txt](https://github.com/Open-MSS/MSS/files/7216839/onetrack.kml.txt)
> 
> Interesting. Both paths are subject to the known issue, but why they show different artefacts is beyond me. I do not judge this to be a problem itself, but it may hint at an underlying one.

It is point 6, not correct readed above. 51.35, 164.4 connected to 66.44, -101.88 
The question would als be which location is correct (flighttrack fits to the axis)

[two_points.ftml.txt](https://github.com/Open-MSS/MSS/files/7217025/two_points.ftml.txt)
the kml was created based on the ftml
[two_points.kml.txt](https://github.com/Open-MSS/MSS/files/7217034/two_points.kml.txt)

line

I have not found how I can trigger the WP to follow the path of the kml line.

**Comment by joernu76** [comment]
> > > We don't have these quite large distances. I do see here a difference between point 8 connecting to western
> > > edgecase
> > > [onetrack.ftml.txt](https://github.com/Open-MSS/MSS/files/7216838/onetrack.ftml.txt)
> > > [onetrack.kml.txt](https://github.com/Open-MSS/MSS/files/7216839/onetrack.kml.txt)
> > 
> > 
> > Interesting. Both paths are subject to the known issue, but why they show different artefacts is beyond me. I do not judge this to be a problem itself, but it may hint at an underlying one.
> 
> It is point 6, not correct readed above. 51.35, 164.4 connected to 66.44, -101.88
> The question would als be which location is correct (flighttrack fits to the axis)
> 
> [two_points.ftml.txt](https://github.com/Open-MSS/MSS/files/7217025/two_points.ftml.txt)
> the kml was created based on the ftml
> [two_points.kml.txt](https://github.com/Open-MSS/MSS/files/7217034/two_points.kml.txt)
> 
> line
> 
> I have not found how I can trigger the WP to follow the path of the kml line.

I interpret it in the way that point 6 is the same in both, but the connection between 5 and 6 is plotted differently.

Regardless, I found that basemap has a function similar to path_points, which is used for the horizontal path. I use the same one now for the KML stuff. Presumably it's faster, certainly, it's out out our backyard.

KML has now the same defect behaviour when "wrapping around" as the flightpath.

**Comment by joernu76** [comment]
So... I dug a bit deeper. Now, both plots should not have that horizontal line. However, the cylindric "projection" is pretty unstable with the left/right boundary. This fixes a couple of issues and makes the behaviour in "sane" use cases better. I do not think, it breaks something, but zooming out on a cylindric map beyond 360° horizontally will not function as any sane person would expect.

**Review by ReimarBauer — DISMISSED** [review]
big improvement, Thx :)

**Review by ReimarBauer — APPROVED** [review]

**Pull request merged**
