### PR TITLE
Add more shortcut functionality

### PR DESCRIPTION
**Pull request by Marilyth**
Partially implements #1153 

Expands the shortcuts by:
- Execute shortcut through double clicking
- Include non-shortcut object if so desired
- Highlight currently selected shortcut with a yellow background
- Include a filter
- Add Ctrl+F Shortcut to directly search for plain text in the UI via the shortcuts dialog

### CODE REVIEW

**Comment by ReimarBauer** [comment]
great to enhance by "Advanced Settings" the information density

The list shows a ":" I've no idea what is connected to that, the redraw button starts with `&R...`
There also some to select which are in menus 

example

Would it be posible to show a tooltip, when it is selected? 

Or a checkbox to extend to tooltips and to have it disabled on default?

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
see coment

**Comment by Marilyth** [comment]
Hovering over an item now reveals all available information about it.

**Review by ReimarBauer — CHANGES_REQUESTED** [review]
That feature showing ObjectName gets a very good development feature too. Great!

Found a small problem,
two_selections

that happens when I select with "Show items without shortcut" enabled in Text Type. Then  toggle "Show items without shortcut" to disabled and switch Display type to ObjectName. Afterwards select something.

**Comment by Marilyth** [comment]
Should be fixed now

**Review by ReimarBauer — APPROVED** [review]

**Pull request merged**
